#!/usr/bin/env bash
# verify.sh — Phase B evidence-pack verification for Lab 22
# (appinsights-connection-string-missing).
#
# File purpose
# ------------
# Phase B verify.sh — pure file processor — emits 4 falsifiable gate JSONs
# from committed canonical evidence. This script reads ONLY the canonical
# 00-/01-/.../15- + A1-/A2-/A3- evidence files already checked into
# `labs/appinsights-connection-string-missing/evidence/` and writes the
# derived gate outputs:
#
#   - 16-cohort-integrity-gate.json
#   - 17-failure-attribution-gate.json
#   - 18-recovery-materialization-gate.json
#   - 19-single-variable-falsification-gate.json
#
# It MUST NOT call Azure, curl remote endpoints, or depend on any live cloud
# state. A reviewer must be able to re-run this script after the lab RG has
# been deleted and still obtain the same verdict from the same committed
# evidence.
#
# Lab 22 binding directives (carried forward from Lab 21 Oracle review)
# ---------------------------------------------------------------------
#   Q1 (cohort binding): Bound every absence predicate to the failed-cohort
#       anchor. Gate 17 sub-gates (b)/(c) (AppRequests/AppTraces empty) are
#       interpretable as missing-env-var evidence ONLY when read together
#       with sub-gate (a) (env=null on the :v3 image's "app" container) AND
#       sub-gate (d) (the app served 20 HTTP 200 during the before-fix
#       window). Without (a)+(d), "AI tables empty" could mean SDK broken /
#       workspace misrouted / no traffic — none attributable to the missing
#       env var.
#
#   Q2 (single canonical source): Each predicate input is read from its
#       single canonical Phase A capture file. There is no dual-path
#       scaffolding for any claim that is NOT a genuinely-equivalent
#       manifestation. The only dual-path sub-gates in this verifier are
#       Gate 16 (a), (b), (c), (d) — cohort integrity tolerates a small
#       fallback band for capture variance but rejects any non-junk extras
#       and any missing canonical file.
#
#   Q3 (PII in same Phase B PR): All gate JSONs have PII placeholders
#       (00000000-0000-0000-0000-000000000000 GUIDs, user@example.com,
#       AAAA…A custom-domain-verification IDs) committed in the canonical
#       inputs already; this script does not re-introduce raw PII.
#
#   Q4 (timestamp backfill disclosure): The Lab 22 canonical inputs do NOT
#       carry a backfilled-timestamp caveat — the 02-/08- traffic-completed
#       files are single-line ISO timestamps captured at runtime by
#       fix-and-capture.sh (formerly verify.sh), and the temporal-coherence
#       sub-gate (Gate 16 sub-gate (b)) reads these runtime-captured files
#       directly. No backfill present, none used.
#
#   Q5 (informational vs gated): The A1/A2/A3 honest-disclosure files
#       document the :v1 UNGUARDED SDK crash variant for transparency.
#       They are PART OF THE COHORT (Gate 16 sub-gate (a) counts them) but
#       are NOT predicates of any failure-attribution or recovery gate.
#       The lab's canonical falsification pair is the :v3 before/after run.
#
# Numbered prefix policy
# ----------------------
# 00-/01-/.../15- + A1-/A2-/A3- = canonical committed evidence inputs
#   (Phase A outputs). This lab uses 00 for trigger+verify run logs,
#   01-15 for the H1+H2 capture sequence, and A1-A3 for honest-disclosure
#   files documenting the :v1 UNGUARDED SDK crash variant.
# 16-/17-/18-/19- = derived Phase B gate outputs generated by this script.
#
# The 16-19 prefix is intentional — it avoids collision with the canonical
# 15- file already in the cohort (15-ai-requests-detail-after-fix.json) and
# does not overwrite any Phase A artifact. Each lab's Phase B output prefix
# is chosen to skip past the highest canonical Phase A prefix in its cohort.
#
# What the four gates prove
# -------------------------
# Gate 16 = cohort integrity gate.
#   Claim: the canonical evidence pack is internally coherent before any
#   hypothesis reasoning starts. This gate consumes the 20 canonical files
#   but reasons about presence, temporal coherence of the before/after
#   traffic-completed UTC stamps, no-extras, and README cross-reference
#   only.
#
# Gate 17 = failure attribution gate.
#   Claim: the before-fix cohort carries the missing-env-var anchor
#   (01-env-before-fix.env is None on the :v3 image's "app" container)
#   AND exhibits the absence cohort (AppRequests empty, AppTraces empty)
#   AND the app served HTTP 200 throughout the capture window (so the
#   absence is attributable to missing instrumentation, NOT to the app
#   being down). This is the H1 falsification check.
#   All four sub-gates use single-path predicates per Oracle Q2 directive,
#   plus a cohort_binding_note that explicitly forbids reading sub-gates
#   (b)/(c) without sub-gates (a)+(d).
#
# Gate 18 = recovery materialization gate.
#   Claim: after the operator adds APPLICATIONINSIGHTS_CONNECTION_STRING
#   via `az containerapp update --set-env-vars`, the App Insights `requests`
#   table shows exactly [["unknown_service", 20]], the `traces` table shows
#   exactly [["unknown_service", 21]], the per-message trace records show
#   exactly 1 startup + 20 endpoint-hit messages corroborating the
#   aggregate 21, and 00-verify-run.txt shows 20 fresh HTTP 200 responses
#   plus the literal recovery PASS marker. Single-path per Oracle Q2.
#
# Gate 19 = single-variable falsification gate.
#   Claim: the recovery is IN-PLACE — the same Container App resource
#   identity transitions from the before-fix cohort to the after-fix
#   cohort by changing only the template.containers[0].env field while
#   keeping the same :v3 image, the same "app" container name, and the
#   same ACR login server registry prefix. Sub-gate (a) compares
#   `template.containers[0]` of 05- and 11- configs as JSON serialized
#   with `sort_keys=True` AFTER removing the `env` key from both —
#   this isolates the env-only delta from unrelated systemData timestamps
#   that the whole-file byte comparison would erroneously include.
#   Sub-gate (b) anchors the falsification pair (--0000006 hasConnStr=false
#   pre-fix, --0000007 hasConnStr=true active=true post-fix) from
#   14-revisions-lifecycle.json. Sub-gate (c) confirms same ACR registry
#   prefix and same "app" container name across the before/after pair.
#   Single-path per Oracle Q2.
#
# Verdict semantics encoded by this script
# ----------------------------------------
# Gate 16 PASS = the evidence cohort is internally consistent.
# Gate 17 PASS = the before-fix cohort is fully attributable to the missing
#   APPLICATIONINSIGHTS_CONNECTION_STRING env var (H1 not falsified).
# Gate 18 PASS = the env-var addition materialized end-to-end telemetry
#   in App Insights (H2 not falsified).
# Gate 19 PASS = the recovery is in-place (same app, same image, same
#   container, same registry — only the env-var delta).
#
# Gate 17 + Gate 18 together encode the lab's main claim: the presence of
# APPLICATIONINSIGHTS_CONNECTION_STRING is the single controlling variable
# for whether App Insights ingests telemetry from this app. Gate 19
# strengthens this by proving the recovery does not depend on changing
# any other resource identity.
#
# Claim ceiling (strict)
# ----------------------
# The supported claim from this evidence is:
#   "In this 2026-06-22 koreacentral reproduction, an Azure Container App
#    running the :v3 image (Flask + azure-monitor-opentelemetry==1.6.4
#    with configure_azure_monitor() guarded by an env-var presence check)
#    serves HTTP 200 to clients but emits zero telemetry to Application
#    Insights when APPLICATIONINSIGHTS_CONNECTION_STRING is unset, and
#    setting that env var via `az containerapp update --set-env-vars`
#    causes the AppRequests and AppTraces tables to populate within the
#    documented ingestion latency."
# NOT:
#   "All Application Insights SDK paths require this env var."
#   "App Insights ingestion always completes within N seconds."
#   "Container App identity is preserved across all env-var updates."
# The honest-disclosure caveats in lab README + evidence/README.md
# document the empirical scope of this reproduction (including the :v1
# UNGUARDED variant that crashes at import and the :v2 Flask-import-order
# variant that silently fails instrumentation despite the env var being
# set).
#
# QUOTED heredoc rule (mandatory)
# -------------------------------
# ALL Python heredocs in this file MUST use `<<'PY'` (single-quoted
# delimiter) to prevent shell expansion of `$` characters inside Python
# code. This is a Lab 14 lesson 29 mandatory rule. Unquoted `<<PY` would
# cause `$variable` in Python to be silently replaced by bash before the
# heredoc reaches python3.
#
# REPO_RELATIVE_EVIDENCE_DIR rule (mandatory)
# -------------------------------------------
# All gate JSONs MUST cite predicate inputs as repo-relative paths (for
# example `labs/appinsights-connection-string-missing/evidence/01-env-before-fix.json`),
# NOT absolute paths. This prevents `/Users/<alias>/...` leakage into
# committed evidence and keeps the pack reproducible across operator
# machines.
#
# Record-scoped predicate rule (mandatory)
# ----------------------------------------
# Lab 15 lesson 34 — no whole-file substring searches. Every JSON
# predicate parses with `json.load()` and iterates parsed records. Only
# 00-trigger-run.txt and 00-verify-run.txt (human-readable run logs) are
# allowed to use string-level predicates, and even there the predicate
# is line-scoped (split on `\n`, strip, check `startswith()` and
# substring membership of a fixed marker token) — NOT whole-file regex.
#
# BOTH-not-OR rule (Lab 19 P0 lesson)
# ----------------------------------
# Where a hypothesis claim is about multiple required conditions, the
# gate predicate uses AND (not OR) between the conditions. Gate 17
# sub-gate (a) requires (env is None) AND (image endswith :v3) AND
# (containerName == "app") simultaneously. Gate 18 sub-gate (a) requires
# the env var to be PRESENT AND the image to still be :v3. Gate 18
# sub-gates (b)/(c) require EXACTLY 1 row AND that row to equal the
# expected ["unknown_service", N] tuple. Gate 18 sub-gate (d) requires
# all three message-count conditions simultaneously (21 total AND 1
# startup AND 20 endpoint). Gate 19 sub-gate (b) requires both anchor
# records to be present with both image-suffix AND hasConnStr AND
# active flags satisfied per record.
#
# Failed-cohort binding rule
# --------------------------
# Gate 17's absence predicates (AppRequests empty, AppTraces empty) are
# interpretable as evidence ONLY when read together with the anchor
# predicates (env is None on the :v3 "app" container AND the app served
# 20 HTTP 200). A reader cannot interpret "AppRequests is empty" as
# "missing env var caused no telemetry" without those anchors — empty
# tables could mean the SDK is broken, the workspace is misrouted, the
# query is wrong, or there was simply no traffic. The gate JSON
# encodes this via a top-level `cohort_binding_note` field and by
# colocating all four sub-gates' predicate_inputs in the same JSON.
#
# Canonical evidence consumed by this script
# ------------------------------------------
# Gate 16 consumes:
#   ALL 20 canonical files (presence + temporal + extras + README)
#
# Gate 17 consumes:
#   00-trigger-run.txt                           (20 HTTP 200 lines — availability anchor)
#   01-env-before-fix.json                       (env=null on :v3 "app" container — missing-env anchor)
#   03-ai-requests-before-fix.json               (tables[0].rows == [])
#   04-ai-traces-before-fix.json                 (tables[0].rows == [])
#
# Gate 18 consumes:
#   00-verify-run.txt                            (20 fresh HTTP 200 + recovery PASS marker)
#   07-env-after-fix.json                        (env var present, image still :v3)
#   09-ai-requests-after-fix.json                (tables[0].rows == [["unknown_service", 20]])
#   10-ai-traces-after-fix.json                  (tables[0].rows == [["unknown_service", 21]])
#   13-ai-traces-messages-after-fix.json         (21 records: 1 startup + 20 endpoint hits)
#
# Gate 19 consumes:
#   05-containerapp-full-config-before-fix.json  (template.containers[0] before — env absent)
#   11-containerapp-full-config-after-fix.json   (template.containers[0] after — env present, 1 element)
#   14-revisions-lifecycle.json                  (--0000006 pre-fix pair, --0000007 post-fix pair)
#
# Files explicitly NOT consumed by this script (Phase B gate inputs)
# ------------------------------------------------------------------
# These canonical files are part of the cohort (Gate 16 checks their
# presence) but are NOT used as predicate inputs by Gates 17-19:
#   - 02-traffic-completed-before-fix.txt   (Gate 16 sub-gate (b) only — temporal anchor)
#   - 06-env-telemetry-config.json          (env-level OTel config; descriptive only)
#   - 08-traffic-completed-after-fix.txt    (Gate 16 sub-gate (b) only — temporal anchor)
#   - 12-kql-requests-timeline.json         (binned-timeline corroboration; descriptive only)
#   - 15-ai-requests-detail-after-fix.json  (per-request detail; descriptive only)
#   - A1-v1-unguarded-sdk-crash-logs.json   (HONEST DISCLOSURE — :v1 variant only; descriptive)
#   - A2-v1-unguarded-crashloop-replica-state.json  (HONEST DISCLOSURE — :v1 variant only; descriptive)
#   - A3-revisions-pre-patch.json           (HONEST DISCLOSURE — pre-patch revisions; descriptive)
#
# Usage
# -----
#   bash labs/appinsights-connection-string-missing/verify.sh
#
# No environment variables are required.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_DIR="$SCRIPT_DIR"
EVIDENCE_DIR="$LAB_DIR/evidence"
REPO_RELATIVE_EVIDENCE_DIR="labs/appinsights-connection-string-missing/evidence"
UTC_NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Canonical input files (Phase A outputs, 20 files).
TRIGGER_LOG_FILE="$EVIDENCE_DIR/00-trigger-run.txt"
VERIFY_LOG_FILE="$EVIDENCE_DIR/00-verify-run.txt"
ENV_BEFORE_FILE="$EVIDENCE_DIR/01-env-before-fix.json"
TRAFFIC_COMPLETED_BEFORE_FILE="$EVIDENCE_DIR/02-traffic-completed-before-fix.txt"
AI_REQUESTS_BEFORE_FILE="$EVIDENCE_DIR/03-ai-requests-before-fix.json"
AI_TRACES_BEFORE_FILE="$EVIDENCE_DIR/04-ai-traces-before-fix.json"
CONFIG_BEFORE_FILE="$EVIDENCE_DIR/05-containerapp-full-config-before-fix.json"
ENV_TELEMETRY_FILE="$EVIDENCE_DIR/06-env-telemetry-config.json"
ENV_AFTER_FILE="$EVIDENCE_DIR/07-env-after-fix.json"
TRAFFIC_COMPLETED_AFTER_FILE="$EVIDENCE_DIR/08-traffic-completed-after-fix.txt"
AI_REQUESTS_AFTER_FILE="$EVIDENCE_DIR/09-ai-requests-after-fix.json"
AI_TRACES_AFTER_FILE="$EVIDENCE_DIR/10-ai-traces-after-fix.json"
CONFIG_AFTER_FILE="$EVIDENCE_DIR/11-containerapp-full-config-after-fix.json"
KQL_TIMELINE_FILE="$EVIDENCE_DIR/12-kql-requests-timeline.json"
AI_TRACES_MESSAGES_FILE="$EVIDENCE_DIR/13-ai-traces-messages-after-fix.json"
REVISIONS_LIFECYCLE_FILE="$EVIDENCE_DIR/14-revisions-lifecycle.json"
AI_REQUESTS_DETAIL_FILE="$EVIDENCE_DIR/15-ai-requests-detail-after-fix.json"
A1_V1_CRASH_FILE="$EVIDENCE_DIR/A1-v1-unguarded-sdk-crash-logs.json"
A2_V1_REPLICA_FILE="$EVIDENCE_DIR/A2-v1-unguarded-crashloop-replica-state.json"
A3_REVS_PRE_PATCH_FILE="$EVIDENCE_DIR/A3-revisions-pre-patch.json"

# Phase B gate output files (16-19 prefix avoids collision with the
# canonical 15- file already in the cohort).
GATE16_FILE="$EVIDENCE_DIR/16-cohort-integrity-gate.json"
GATE17_FILE="$EVIDENCE_DIR/17-failure-attribution-gate.json"
GATE18_FILE="$EVIDENCE_DIR/18-recovery-materialization-gate.json"
GATE19_FILE="$EVIDENCE_DIR/19-single-variable-falsification-gate.json"

for required in \
    "$TRIGGER_LOG_FILE" \
    "$VERIFY_LOG_FILE" \
    "$ENV_BEFORE_FILE" \
    "$TRAFFIC_COMPLETED_BEFORE_FILE" \
    "$AI_REQUESTS_BEFORE_FILE" \
    "$AI_TRACES_BEFORE_FILE" \
    "$CONFIG_BEFORE_FILE" \
    "$ENV_TELEMETRY_FILE" \
    "$ENV_AFTER_FILE" \
    "$TRAFFIC_COMPLETED_AFTER_FILE" \
    "$AI_REQUESTS_AFTER_FILE" \
    "$AI_TRACES_AFTER_FILE" \
    "$CONFIG_AFTER_FILE" \
    "$KQL_TIMELINE_FILE" \
    "$AI_TRACES_MESSAGES_FILE" \
    "$REVISIONS_LIFECYCLE_FILE" \
    "$AI_REQUESTS_DETAIL_FILE" \
    "$A1_V1_CRASH_FILE" \
    "$A2_V1_REPLICA_FILE" \
    "$A3_REVS_PRE_PATCH_FILE"; do
    if [[ ! -f "$required" ]]; then
        echo "ERROR: required canonical evidence file missing: $required" >&2
        echo "This Phase B verify.sh is a pure file processor and cannot synthesize missing evidence." >&2
        exit 1
    fi
done

echo "=== Phase 16: cohort integrity gate ==="
UTC_NOW="$UTC_NOW" \
EVIDENCE_DIR="$EVIDENCE_DIR" \
TRIGGER_LOG_FILE="$TRIGGER_LOG_FILE" \
VERIFY_LOG_FILE="$VERIFY_LOG_FILE" \
ENV_BEFORE_FILE="$ENV_BEFORE_FILE" \
TRAFFIC_COMPLETED_BEFORE_FILE="$TRAFFIC_COMPLETED_BEFORE_FILE" \
AI_REQUESTS_BEFORE_FILE="$AI_REQUESTS_BEFORE_FILE" \
AI_TRACES_BEFORE_FILE="$AI_TRACES_BEFORE_FILE" \
CONFIG_BEFORE_FILE="$CONFIG_BEFORE_FILE" \
ENV_TELEMETRY_FILE="$ENV_TELEMETRY_FILE" \
ENV_AFTER_FILE="$ENV_AFTER_FILE" \
TRAFFIC_COMPLETED_AFTER_FILE="$TRAFFIC_COMPLETED_AFTER_FILE" \
AI_REQUESTS_AFTER_FILE="$AI_REQUESTS_AFTER_FILE" \
AI_TRACES_AFTER_FILE="$AI_TRACES_AFTER_FILE" \
CONFIG_AFTER_FILE="$CONFIG_AFTER_FILE" \
KQL_TIMELINE_FILE="$KQL_TIMELINE_FILE" \
AI_TRACES_MESSAGES_FILE="$AI_TRACES_MESSAGES_FILE" \
REVISIONS_LIFECYCLE_FILE="$REVISIONS_LIFECYCLE_FILE" \
AI_REQUESTS_DETAIL_FILE="$AI_REQUESTS_DETAIL_FILE" \
A1_V1_CRASH_FILE="$A1_V1_CRASH_FILE" \
A2_V1_REPLICA_FILE="$A2_V1_REPLICA_FILE" \
A3_REVS_PRE_PATCH_FILE="$A3_REVS_PRE_PATCH_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE16_FILE"
import json
import os
import pathlib
import re
from datetime import datetime, timezone


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


def sample(items, n=5):
    return items[:n]


canonical_paths = [
    pathlib.Path(os.environ["TRIGGER_LOG_FILE"]),
    pathlib.Path(os.environ["VERIFY_LOG_FILE"]),
    pathlib.Path(os.environ["ENV_BEFORE_FILE"]),
    pathlib.Path(os.environ["TRAFFIC_COMPLETED_BEFORE_FILE"]),
    pathlib.Path(os.environ["AI_REQUESTS_BEFORE_FILE"]),
    pathlib.Path(os.environ["AI_TRACES_BEFORE_FILE"]),
    pathlib.Path(os.environ["CONFIG_BEFORE_FILE"]),
    pathlib.Path(os.environ["ENV_TELEMETRY_FILE"]),
    pathlib.Path(os.environ["ENV_AFTER_FILE"]),
    pathlib.Path(os.environ["TRAFFIC_COMPLETED_AFTER_FILE"]),
    pathlib.Path(os.environ["AI_REQUESTS_AFTER_FILE"]),
    pathlib.Path(os.environ["AI_TRACES_AFTER_FILE"]),
    pathlib.Path(os.environ["CONFIG_AFTER_FILE"]),
    pathlib.Path(os.environ["KQL_TIMELINE_FILE"]),
    pathlib.Path(os.environ["AI_TRACES_MESSAGES_FILE"]),
    pathlib.Path(os.environ["REVISIONS_LIFECYCLE_FILE"]),
    pathlib.Path(os.environ["AI_REQUESTS_DETAIL_FILE"]),
    pathlib.Path(os.environ["A1_V1_CRASH_FILE"]),
    pathlib.Path(os.environ["A2_V1_REPLICA_FILE"]),
    pathlib.Path(os.environ["A3_REVS_PRE_PATCH_FILE"]),
]
evidence_dir = pathlib.Path(os.environ["EVIDENCE_DIR"])
traffic_before_path = pathlib.Path(os.environ["TRAFFIC_COMPLETED_BEFORE_FILE"])
traffic_after_path = pathlib.Path(os.environ["TRAFFIC_COMPLETED_AFTER_FILE"])

# Sub-gate (a): all 20 canonical files exist; fallback requires at least 18.
presence_records = [{"path": repo_rel(p), "exists": p.exists()} for p in canonical_paths]
present_count = sum(1 for item in presence_records if item["exists"])
a_strong_path_all_20_files_exist = present_count == 20
a_fallback_path_at_least_18_files_exist = present_count >= 18
a_pass = a_strong_path_all_20_files_exist or a_fallback_path_at_least_18_files_exist

# Sub-gate (b): temporal coherence. The before-fix traffic-completed
# timestamp (02-traffic-completed-before-fix.txt:1) and the after-fix
# traffic-completed timestamp (08-traffic-completed-after-fix.txt:1) must
# parse as strict ISO-8601 UTC ending in "Z", be monotonic
# (before<=after), and span <= 30 minutes (strong) / <= 60 minutes
# (fallback). This proves the cohort was captured as one coherent
# sequence within the App Insights ingestion-latency window, not stitched
# from disparate runs.
#
# Unlike acr-pull-failure (which extracts ISO from the trigger-run line 1),
# this lab's run-log files do NOT carry a leading ISO timestamp — they
# start with "[script-name] starting (UTC...)" non-ISO prose. The
# 02-/08- files are single-line ISO-only artifacts captured at runtime
# by trigger.sh / fix-and-capture.sh after the 20-request traffic burst
# completes, which is exactly the temporal anchor we want for cohort
# coherence (the AI-table-query window starts after these timestamps).
STRICT_ISO_RE = re.compile(r"^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})Z$")
b_temporal_records = {}
b_strong_path_monotonic_within_30min = False
b_fallback_path_monotonic_within_60min = False
try:
    traffic_before_text = traffic_before_path.read_text().strip()
    traffic_after_text = traffic_after_path.read_text().strip()
    before_match = STRICT_ISO_RE.match(traffic_before_text)
    after_match = STRICT_ISO_RE.match(traffic_after_text)
    before_dt = (
        datetime.fromisoformat(before_match.group(1)).replace(tzinfo=timezone.utc)
        if before_match
        else None
    )
    after_dt = (
        datetime.fromisoformat(after_match.group(1)).replace(tzinfo=timezone.utc)
        if after_match
        else None
    )
    b_temporal_records = {
        "traffic_before_raw": traffic_before_text,
        "traffic_after_raw": traffic_after_text,
        "traffic_before_iso": before_dt.isoformat() if before_dt else None,
        "traffic_after_iso": after_dt.isoformat() if after_dt else None,
        "traffic_before_parsed_strict_iso_utc_z": before_match is not None,
        "traffic_after_parsed_strict_iso_utc_z": after_match is not None,
    }
    if before_dt and after_dt:
        monotonic = before_dt <= after_dt
        span_seconds = (after_dt - before_dt).total_seconds()
        b_temporal_records["monotonic_before_after"] = monotonic
        b_temporal_records["span_seconds_before_to_after"] = span_seconds
        b_strong_path_monotonic_within_30min = monotonic and span_seconds <= 30 * 60
        b_fallback_path_monotonic_within_60min = monotonic and span_seconds <= 60 * 60
    else:
        b_temporal_records["parse_error"] = "one_or_both_traffic_completed_files_not_strict_iso_utc_z"
except (ValueError, OSError) as exc:
    b_temporal_records = {
        "parse_error": str(exc),
        "traffic_before_path": repo_rel(traffic_before_path),
        "traffic_after_path": repo_rel(traffic_after_path),
    }
b_pass = b_strong_path_monotonic_within_30min or b_fallback_path_monotonic_within_60min

# Sub-gate (c): no unexpected non-junk extras. Lab 19 P0 lesson — the
# fallback path must REJECT any non-junk extras, not just check for junk
# patterns. Phase B outputs (16-19 gate JSONs) and README.md are expected
# and excluded; everything else outside the canonical 20 is an unexpected
# extra unless it matches the allowed-junk pattern.
canonical_names = {p.name for p in canonical_paths}
phase_b_outputs = {
    "16-cohort-integrity-gate.json",
    "17-failure-attribution-gate.json",
    "18-recovery-materialization-gate.json",
    "19-single-variable-falsification-gate.json",
}
expected_meta = {"README.md"}
actual_names = {p.name for p in evidence_dir.iterdir() if p.is_file()}
extras_found = sorted(actual_names - canonical_names - phase_b_outputs - expected_meta)
missing_canonical = sorted(canonical_names - actual_names)

ALLOWED_JUNK_SUFFIXES = (".swp", ".bak", ".tmp", ".swo", ".orig")
ALLOWED_JUNK_EXACT_NAMES = (".DS_Store", "Thumbs.db")


def is_allowed_junk(name):
    return (
        name in ALLOWED_JUNK_EXACT_NAMES
        or any(name.endswith(suffix) for suffix in ALLOWED_JUNK_SUFFIXES)
    )


unexpected_non_junk_extras = [f for f in extras_found if not is_allowed_junk(f)]
c_strong_path_exact_match = len(extras_found) == 0 and len(missing_canonical) == 0
c_fallback_path_no_foreign_files = (
    len(missing_canonical) == 0 and len(unexpected_non_junk_extras) == 0
)
c_pass = c_strong_path_exact_match or c_fallback_path_no_foreign_files

# Sub-gate (d): README.md cross-references all 4 Phase B gate JSON
# filenames. Strong path requires the README to mention every gate JSON
# by exact name; fallback path requires the README file to exist (so a
# future maintainer at least has a starting point for the provenance
# trail).
readme_path = evidence_dir / "README.md"
d_readme_exists = readme_path.exists()
d_strong_path_readme_references_all_gates = False
d_fallback_path_readme_exists = d_readme_exists
gate_reference_records = []
if d_readme_exists:
    readme_text = readme_path.read_text()
    gate_reference_records = [
        {"gate_filename": gate_name, "mentioned_in_readme": gate_name in readme_text}
        for gate_name in sorted(phase_b_outputs)
    ]
    d_strong_path_readme_references_all_gates = all(
        item["mentioned_in_readme"] for item in gate_reference_records
    )
d_pass = d_strong_path_readme_references_all_gates or d_fallback_path_readme_exists

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "appinsights_connection_string_missing",
    "hypothesis": "H_cohort_integrity",
    "claim": "evidence_cohort_is_internally_consistent_and_temporally_coherent",
    "claim_level": "Observed",
    "predicate_inputs": {
        "evidence_dir": os.environ["REPO_RELATIVE_EVIDENCE_DIR"],
        "canonical_files_manifest": sorted(canonical_names),
        "phase_b_outputs_manifest": sorted(phase_b_outputs),
        "expected_meta_files": sorted(expected_meta),
    },
    "sub_gate_a_predicate": (
        "All 20 canonical Phase A files exist; fallback requires at least 18."
    ),
    "sub_gate_b_predicate": (
        "Before-fix traffic-completed timestamp (02-traffic-completed-before-fix.txt:1) "
        "and after-fix traffic-completed timestamp (08-traffic-completed-after-fix.txt:1) "
        "both parse as strict ISO-8601 UTC (YYYY-MM-DDTHH:MM:SSZ), are monotonic, and "
        "span <= 30 minutes (strong) / <= 60 minutes (fallback). Both files are "
        "single-line runtime captures from trigger.sh / fix-and-capture.sh — NO "
        "backfilled timestamps in this lab."
    ),
    "sub_gate_c_predicate": (
        "No unexpected non-junk extras under evidence/. Strong path requires exact match "
        "of the canonical 20 + 4 Phase B outputs + README.md; fallback tolerates only "
        "editor/OS junk (.swp/.bak/.tmp/.swo/.orig/.DS_Store/Thumbs.db) and STILL "
        "requires zero missing canonical files."
    ),
    "sub_gate_d_predicate": (
        "evidence/README.md cross-references all 4 Phase B gate JSON filenames; "
        "fallback requires only that README.md exists."
    ),
    "required_canonical_file_count": 20,
    "minimum_fallback_file_count": 18,
    "sub_gate_a_canonical_files_present": {
        "observed_present_file_count": present_count,
        "observed_first_5": sample(presence_records),
        "a_strong_path_all_20_files_exist": a_strong_path_all_20_files_exist,
        "a_fallback_path_at_least_18_files_exist": a_fallback_path_at_least_18_files_exist,
        "a_pass": a_pass,
    },
    "sub_gate_b_temporal_coherence": {
        "observed_temporal_records": b_temporal_records,
        "b_strong_path_monotonic_within_30min": b_strong_path_monotonic_within_30min,
        "b_fallback_path_monotonic_within_60min": b_fallback_path_monotonic_within_60min,
        "b_pass": b_pass,
    },
    "sub_gate_c_no_unexpected_extras": {
        "observed_extras_count": len(extras_found),
        "observed_extras": extras_found,
        "observed_missing_canonical": missing_canonical,
        "unexpected_non_junk_extras": unexpected_non_junk_extras,
        "allowed_junk_suffixes": list(ALLOWED_JUNK_SUFFIXES),
        "allowed_junk_exact_names": list(ALLOWED_JUNK_EXACT_NAMES),
        "c_strong_path_exact_match": c_strong_path_exact_match,
        "c_fallback_path_no_foreign_files": c_fallback_path_no_foreign_files,
        "c_pass": c_pass,
    },
    "sub_gate_d_readme_references_gate_outputs": {
        "observed_readme_exists": d_readme_exists,
        "observed_gate_reference_records": gate_reference_records,
        "d_strong_path_readme_references_all_gates": d_strong_path_readme_references_all_gates,
        "d_fallback_path_readme_exists": d_fallback_path_readme_exists,
        "d_pass": d_pass,
    },
}
result["appinsights_h_cohort_integrity_sub_gates"] = {
    "a_canonical_files_present": result["sub_gate_a_canonical_files_present"]["a_pass"],
    "b_temporal_coherence": result["sub_gate_b_temporal_coherence"]["b_pass"],
    "c_no_unexpected_extras": result["sub_gate_c_no_unexpected_extras"]["c_pass"],
    "d_readme_references_gate_outputs": result["sub_gate_d_readme_references_gate_outputs"]["d_pass"],
}
result["appinsights_h_cohort_integrity_all_subgates_pass"] = all(
    result["appinsights_h_cohort_integrity_sub_gates"].values()
)
result["gate_classification"] = "evidence_cohort_is_internally_consistent_and_temporally_coherent"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 17: failure attribution gate ==="
UTC_NOW="$UTC_NOW" \
TRIGGER_LOG_FILE="$TRIGGER_LOG_FILE" \
ENV_BEFORE_FILE="$ENV_BEFORE_FILE" \
AI_REQUESTS_BEFORE_FILE="$AI_REQUESTS_BEFORE_FILE" \
AI_TRACES_BEFORE_FILE="$AI_TRACES_BEFORE_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE17_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


trigger_log_path = pathlib.Path(os.environ["TRIGGER_LOG_FILE"])
env_before_path = pathlib.Path(os.environ["ENV_BEFORE_FILE"])
ai_requests_before_path = pathlib.Path(os.environ["AI_REQUESTS_BEFORE_FILE"])
ai_traces_before_path = pathlib.Path(os.environ["AI_TRACES_BEFORE_FILE"])

env_before = json.loads(env_before_path.read_text())
ai_requests_before = json.loads(ai_requests_before_path.read_text())
ai_traces_before = json.loads(ai_traces_before_path.read_text())

EXPECTED_IMAGE_SUFFIX = ":v3"
EXPECTED_CONTAINER_NAME = "app"
EXPECTED_REQUEST_COUNT = 20
EXPECTED_TOTAL_LOG_LINE_COUNT = 93
HTTP_200_MARKER = "HTTP 200"
REQUEST_LINE_PREFIX = "request "

# Sub-gate (a): missing-env-var anchor. The before-fix env capture shows
# env=null on the :v3 image's "app" container. Single-path BOTH-not-OR:
# all three conditions (env is None AND image endswith :v3 AND
# containerName == "app") must hold simultaneously to anchor the cohort
# to the missing-env-var failure mode.
observed_env_field = env_before.get("env")
observed_image = env_before.get("image")
observed_container_name = env_before.get("containerName")
a_env_is_none = observed_env_field is None
a_image_ends_v3 = (
    isinstance(observed_image, str)
    and observed_image.endswith(EXPECTED_IMAGE_SUFFIX)
)
a_container_name_is_app = observed_container_name == EXPECTED_CONTAINER_NAME
a_predicate_holds = a_env_is_none and a_image_ends_v3 and a_container_name_is_app
a_pass = a_predicate_holds

# Sub-gate (b): AppRequests empty. Record-scoped: parse tables[0].rows
# and assert exact equality with []. Single-path. Bound to the failed
# cohort: this absence is only interpretable as "missing env var caused
# no telemetry" when read with sub-gates (a) AND (d).
ai_requests_tables = ai_requests_before.get("tables") or []
ai_requests_first_table = ai_requests_tables[0] if ai_requests_tables else {}
ai_requests_rows = ai_requests_first_table.get("rows")
b_predicate_holds = ai_requests_rows == []
b_pass = b_predicate_holds

# Sub-gate (c): AppTraces empty. Same shape as (b). Single-path. Same
# cohort binding.
ai_traces_tables = ai_traces_before.get("tables") or []
ai_traces_first_table = ai_traces_tables[0] if ai_traces_tables else {}
ai_traces_rows = ai_traces_first_table.get("rows")
c_predicate_holds = ai_traces_rows == []
c_pass = c_predicate_holds

# Sub-gate (d): availability anchor. 00-trigger-run.txt must contain
# exactly 20 lines matching the pattern "request NN -> HTTP 200" (after
# stripping leading whitespace) AND the file's total line count must be
# exactly 93 (the canonical length of the captured trigger.sh log).
# Line-scoped (split on \n, strip, check startswith() + substring), NOT
# whole-file regex. This sub-gate transforms (b)/(c) from "tables empty"
# (could mean anything) into "tables empty WHILE the app was healthy AND
# serving traffic" — which is what makes the absence diagnostic for
# missing instrumentation. The total-line-count check guards against
# truncated or augmented trigger logs that would still happen to contain
# 20 HTTP 200 lines but differ in their surrounding context (a different
# pre-traffic capture sequence would change the line count).
trigger_log_lines = trigger_log_path.read_text().splitlines()
http_200_request_lines = []
for raw_line in trigger_log_lines:
    stripped = raw_line.strip()
    if stripped.startswith(REQUEST_LINE_PREFIX) and HTTP_200_MARKER in stripped:
        http_200_request_lines.append(stripped)
observed_http_200_count = len(http_200_request_lines)
observed_total_log_lines = len(trigger_log_lines)
d_http_200_count_matches = observed_http_200_count == EXPECTED_REQUEST_COUNT
d_total_log_lines_matches = observed_total_log_lines == EXPECTED_TOTAL_LOG_LINE_COUNT
d_predicate_holds = d_http_200_count_matches and d_total_log_lines_matches
d_pass = d_predicate_holds

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "appinsights_connection_string_missing",
    "hypothesis": "H1_failure_attribution",
    "claim": "before_fix_signature_consistent_with_missing_applicationinsights_connection_string",
    "claim_level": "Observed",
    "predicate_inputs": {
        "trigger_log_path": repo_rel(trigger_log_path),
        "env_before_path": repo_rel(env_before_path),
        "ai_requests_before_path": repo_rel(ai_requests_before_path),
        "ai_traces_before_path": repo_rel(ai_traces_before_path),
    },
    "thresholds": {
        "expected_image_suffix": EXPECTED_IMAGE_SUFFIX,
        "expected_container_name": EXPECTED_CONTAINER_NAME,
        "expected_request_count": EXPECTED_REQUEST_COUNT,
        "expected_total_log_line_count": EXPECTED_TOTAL_LOG_LINE_COUNT,
        "http_200_marker": HTTP_200_MARKER,
        "request_line_prefix": REQUEST_LINE_PREFIX,
    },
    "cohort_binding_note": (
        "Sub-gates (b) and (c) are absence predicates (AppRequests empty / AppTraces "
        "empty) that are interpretable as missing-env-var evidence ONLY in "
        "conjunction with sub-gate (a) (env=null on the :v3 'app' container) AND "
        "sub-gate (d) (the app served 20 HTTP 200 during the before-fix capture "
        "window). Without (a)+(d), 'AI tables empty' could mean SDK is broken / "
        "workspace is misrouted / query is wrong / no traffic was sent — none "
        "of which is attributable to the missing APPLICATIONINSIGHTS_CONNECTION_STRING "
        "env var. The predicate_inputs block colocates the anchor and the absences "
        "in the same gate JSON so a reader cannot interpret them separately. "
        "Additionally, full attribution to the missing env var as the UNIQUE cause "
        "of the silent gap requires reading this gate together with Gate 18 "
        "(recovery materialization proves adding the env var was sufficient) AND "
        "Gate 19 (single-variable falsification proves nothing else changed between "
        "the before-fix and after-fix configs). Gate 17 alone proves the before-fix "
        "signature is CONSISTENT WITH the missing-env-var hypothesis, NOT that the "
        "missing env var is the UNIQUE cause of the silent observability gap — that "
        "stronger claim is only earned by reading Gates 17 + 18 + 19 together."
    ),
    "sub_gate_a_predicate": (
        "01-env-before-fix.env is None AND .image endswith ':v3' AND "
        ".containerName == 'app' (BOTH-not-OR across all three conditions). "
        "Single-path. Record-scoped: parsed JSON field reads."
    ),
    "sub_gate_b_predicate": (
        "03-ai-requests-before-fix.tables[0].rows == [] (exact equality, single-path). "
        "Record-scoped: parsed JSON array equality, not greppy substring."
    ),
    "sub_gate_c_predicate": (
        "04-ai-traces-before-fix.tables[0].rows == [] (exact equality, single-path). "
        "Record-scoped: parsed JSON array equality, not greppy substring."
    ),
    "sub_gate_d_predicate": (
        "00-trigger-run.txt contains exactly 20 lines matching pattern "
        "stripped.startswith('request ') AND 'HTTP 200' in stripped, AND "
        "the file's total line count is exactly 93 (BOTH-not-OR across "
        "both conditions). Line-scoped: split on newline, strip, "
        "prefix-and-substring check; NOT whole-file regex. This availability "
        "anchor makes (b)/(c) attributable to missing instrumentation rather "
        "than 'app down'. The total-line-count check guards against truncated "
        "or augmented trigger logs that would still happen to contain 20 "
        "HTTP 200 lines but differ in their surrounding context."
    ),
    "sub_gate_a_missing_env_var_anchor": {
        "observed_env_field": observed_env_field,
        "observed_image": observed_image,
        "observed_container_name": observed_container_name,
        "observed_env_is_none": a_env_is_none,
        "observed_image_ends_v3": a_image_ends_v3,
        "observed_container_name_is_app": a_container_name_is_app,
        "a_predicate_holds": a_predicate_holds,
        "a_pass": a_pass,
    },
    "sub_gate_b_ai_requests_empty": {
        "observed_ai_requests_rows": ai_requests_rows,
        "observed_ai_requests_row_count": (
            len(ai_requests_rows) if isinstance(ai_requests_rows, list) else None
        ),
        "b_predicate_holds": b_predicate_holds,
        "b_pass": b_pass,
    },
    "sub_gate_c_ai_traces_empty": {
        "observed_ai_traces_rows": ai_traces_rows,
        "observed_ai_traces_row_count": (
            len(ai_traces_rows) if isinstance(ai_traces_rows, list) else None
        ),
        "c_predicate_holds": c_predicate_holds,
        "c_pass": c_pass,
    },
    "sub_gate_d_availability_anchor_20_http_200": {
        "observed_total_log_lines": observed_total_log_lines,
        "observed_http_200_count": observed_http_200_count,
        "observed_first_5_http_200_lines": http_200_request_lines[:5],
        "observed_http_200_count_matches": d_http_200_count_matches,
        "observed_total_log_lines_matches": d_total_log_lines_matches,
        "d_predicate_holds": d_predicate_holds,
        "d_pass": d_pass,
    },
}
result["appinsights_h1_failure_attribution_sub_gates"] = {
    "a_missing_env_var_anchor": result["sub_gate_a_missing_env_var_anchor"]["a_pass"],
    "b_ai_requests_empty": result["sub_gate_b_ai_requests_empty"]["b_pass"],
    "c_ai_traces_empty": result["sub_gate_c_ai_traces_empty"]["c_pass"],
    "d_availability_anchor_20_http_200": result["sub_gate_d_availability_anchor_20_http_200"]["d_pass"],
}
result["appinsights_h1_failure_attribution_all_subgates_pass"] = all(
    result["appinsights_h1_failure_attribution_sub_gates"].values()
)
result["gate_classification"] = "before_fix_signature_consistent_with_missing_applicationinsights_connection_string"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 18: recovery materialization gate ==="
UTC_NOW="$UTC_NOW" \
VERIFY_LOG_FILE="$VERIFY_LOG_FILE" \
ENV_AFTER_FILE="$ENV_AFTER_FILE" \
AI_REQUESTS_AFTER_FILE="$AI_REQUESTS_AFTER_FILE" \
AI_TRACES_AFTER_FILE="$AI_TRACES_AFTER_FILE" \
AI_TRACES_MESSAGES_FILE="$AI_TRACES_MESSAGES_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE18_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


verify_log_path = pathlib.Path(os.environ["VERIFY_LOG_FILE"])
env_after_path = pathlib.Path(os.environ["ENV_AFTER_FILE"])
ai_requests_after_path = pathlib.Path(os.environ["AI_REQUESTS_AFTER_FILE"])
ai_traces_after_path = pathlib.Path(os.environ["AI_TRACES_AFTER_FILE"])
ai_traces_messages_path = pathlib.Path(os.environ["AI_TRACES_MESSAGES_FILE"])

env_after = json.loads(env_after_path.read_text())
ai_requests_after = json.loads(ai_requests_after_path.read_text())
ai_traces_after = json.loads(ai_traces_after_path.read_text())
ai_traces_messages = json.loads(ai_traces_messages_path.read_text())

EXPECTED_ENV_NAME = "APPLICATIONINSIGHTS_CONNECTION_STRING"
EXPECTED_IMAGE_SUFFIX = ":v3"
EXPECTED_CONTAINER_NAME = "app"
EXPECTED_ROLE_NAME = "unknown_service"
EXPECTED_REQUEST_COUNT = 20
EXPECTED_TRACE_COUNT = 21
EXPECTED_STARTUP_MESSAGE = "Azure Monitor configured: telemetry export enabled"
EXPECTED_ENDPOINT_MESSAGE = "/ endpoint hit (conn_str_present=True)"
EXPECTED_RECOVERY_PASS_MARKER = "PASS: After adding APPLICATIONINSIGHTS_CONNECTION_STRING"
EXPECTED_VERIFY_LOG_LINE_COUNT = 111
HTTP_200_MARKER = "HTTP 200"
REQUEST_LINE_PREFIX = "request "

# Sub-gate (a): env-var present on the same :v3 image AND the same
# container name as the before-fix anchor. Single-path BOTH-not-OR:
# envNames contains APPLICATIONINSIGHTS_CONNECTION_STRING AND image
# endswith :v3 AND containerName == "app". The containerName check is
# what proves the env var landed on the SAME container the before-fix
# capture (Gate 17 sub-gate (a)) anchored on, not a sibling container
# that a parallel template change might have introduced.
observed_env_names = env_after.get("envNames") or []
observed_image = env_after.get("image")
observed_container_name = env_after.get("containerName")
a_env_present = (
    isinstance(observed_env_names, list)
    and EXPECTED_ENV_NAME in observed_env_names
)
a_image_ends_v3 = (
    isinstance(observed_image, str)
    and observed_image.endswith(EXPECTED_IMAGE_SUFFIX)
)
a_container_name_is_app = observed_container_name == EXPECTED_CONTAINER_NAME
a_predicate_holds = a_env_present and a_image_ends_v3 and a_container_name_is_app
a_pass = a_predicate_holds

# Sub-gate (b): AppRequests now exactly [["unknown_service", 20]].
# Single-path BOTH-not-OR: length is exactly 1 AND that 1 row equals
# the expected [role_name, request_count] tuple. Record-scoped JSON
# equality, not greppy substring.
EXPECTED_REQUESTS_ROW = [EXPECTED_ROLE_NAME, EXPECTED_REQUEST_COUNT]
ai_requests_tables = ai_requests_after.get("tables") or []
ai_requests_first_table = ai_requests_tables[0] if ai_requests_tables else {}
ai_requests_rows = ai_requests_first_table.get("rows")
b_rows_is_list = isinstance(ai_requests_rows, list)
b_rows_count_is_1 = b_rows_is_list and len(ai_requests_rows) == 1
b_first_row_matches = (
    b_rows_count_is_1
    and ai_requests_rows[0] == EXPECTED_REQUESTS_ROW
)
b_predicate_holds = b_rows_count_is_1 and b_first_row_matches
b_pass = b_predicate_holds

# Sub-gate (c): AppTraces now exactly [["unknown_service", 21]].
# Same shape as (b). Single-path BOTH-not-OR.
EXPECTED_TRACES_ROW = [EXPECTED_ROLE_NAME, EXPECTED_TRACE_COUNT]
ai_traces_tables = ai_traces_after.get("tables") or []
ai_traces_first_table = ai_traces_tables[0] if ai_traces_tables else {}
ai_traces_rows = ai_traces_first_table.get("rows")
c_rows_is_list = isinstance(ai_traces_rows, list)
c_rows_count_is_1 = c_rows_is_list and len(ai_traces_rows) == 1
c_first_row_matches = (
    c_rows_count_is_1
    and ai_traces_rows[0] == EXPECTED_TRACES_ROW
)
c_predicate_holds = c_rows_count_is_1 and c_first_row_matches
c_pass = c_predicate_holds

# Sub-gate (d): per-message trace records corroborate the aggregate
# count of 21 from sub-gate (c). 13-ai-traces-messages-after-fix.tables[0].rows
# must contain EXACTLY 21 records AND EXACTLY 1 row with message ==
# "Azure Monitor configured: telemetry export enabled" AND EXACTLY 20
# rows with message == "/ endpoint hit (conn_str_present=True)".
# Record-scoped iteration on parsed JSON rows; message column index = 1.
# This sub-gate exists because the aggregate count alone could include
# spurious traces from concurrent processes — the per-message breakdown
# proves the 21 are exactly 1 known-startup + 20 known-endpoint-hits.
ai_traces_messages_tables = ai_traces_messages.get("tables") or []
ai_traces_messages_first_table = (
    ai_traces_messages_tables[0] if ai_traces_messages_tables else {}
)
ai_traces_messages_rows = ai_traces_messages_first_table.get("rows") or []
ai_traces_messages_columns = ai_traces_messages_first_table.get("columns") or []
# Discover message column index defensively; default to 1 if columns
# absent (the canonical schema is [timestamp, message, severityLevel]).
message_column_index = next(
    (idx for idx, col in enumerate(ai_traces_messages_columns) if col.get("name") == "message"),
    1,
)
observed_total_trace_records = len(ai_traces_messages_rows)
startup_count = 0
endpoint_count = 0
for record in ai_traces_messages_rows:
    if not isinstance(record, list) or len(record) <= message_column_index:
        continue
    message_value = record[message_column_index]
    if message_value == EXPECTED_STARTUP_MESSAGE:
        startup_count += 1
    elif message_value == EXPECTED_ENDPOINT_MESSAGE:
        endpoint_count += 1
d_total_count_is_21 = observed_total_trace_records == EXPECTED_TRACE_COUNT
d_startup_count_is_1 = startup_count == 1
d_endpoint_count_is_20 = endpoint_count == EXPECTED_REQUEST_COUNT
d_predicate_holds = d_total_count_is_21 and d_startup_count_is_1 and d_endpoint_count_is_20
d_pass = d_predicate_holds

# Sub-gate (e): 00-verify-run.txt shows 20 fresh HTTP 200 responses AND
# contains the literal recovery PASS marker AND the file's total line
# count is exactly 111. Line-scoped count + substring membership +
# length check. Single-path BOTH-not-OR across all three conditions.
# The total-line-count check guards against truncated or augmented
# fix-and-capture logs that would still happen to contain 20 HTTP 200
# lines and the recovery marker (e.g., a partial rerun that captured
# only the recovery half, or an augmented log with additional spurious
# request lines beyond the canonical 20).
verify_log_text = verify_log_path.read_text()
verify_log_lines = verify_log_text.splitlines()
verify_http_200_request_lines = []
for raw_line in verify_log_lines:
    stripped = raw_line.strip()
    if stripped.startswith(REQUEST_LINE_PREFIX) and HTTP_200_MARKER in stripped:
        verify_http_200_request_lines.append(stripped)
e_observed_http_200_count = len(verify_http_200_request_lines)
e_observed_total_log_lines = len(verify_log_lines)
e_http_200_count_is_20 = e_observed_http_200_count == EXPECTED_REQUEST_COUNT
e_recovery_pass_marker_present = EXPECTED_RECOVERY_PASS_MARKER in verify_log_text
e_total_log_lines_matches = e_observed_total_log_lines == EXPECTED_VERIFY_LOG_LINE_COUNT
e_predicate_holds = (
    e_http_200_count_is_20
    and e_recovery_pass_marker_present
    and e_total_log_lines_matches
)
e_pass = e_predicate_holds

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "appinsights_connection_string_missing",
    "hypothesis": "H2_recovery_materialization",
    "claim": "adding_applicationinsights_connection_string_materialized_end_to_end_telemetry",
    "claim_level": "Observed",
    "predicate_inputs": {
        "verify_log_path": repo_rel(verify_log_path),
        "env_after_path": repo_rel(env_after_path),
        "ai_requests_after_path": repo_rel(ai_requests_after_path),
        "ai_traces_after_path": repo_rel(ai_traces_after_path),
        "ai_traces_messages_path": repo_rel(ai_traces_messages_path),
    },
    "thresholds": {
        "expected_env_name": EXPECTED_ENV_NAME,
        "expected_image_suffix": EXPECTED_IMAGE_SUFFIX,
        "expected_container_name": EXPECTED_CONTAINER_NAME,
        "expected_role_name": EXPECTED_ROLE_NAME,
        "expected_request_count": EXPECTED_REQUEST_COUNT,
        "expected_trace_count": EXPECTED_TRACE_COUNT,
        "expected_startup_message": EXPECTED_STARTUP_MESSAGE,
        "expected_endpoint_message": EXPECTED_ENDPOINT_MESSAGE,
        "expected_recovery_pass_marker": EXPECTED_RECOVERY_PASS_MARKER,
        "expected_verify_log_line_count": EXPECTED_VERIFY_LOG_LINE_COUNT,
        "http_200_marker": HTTP_200_MARKER,
        "request_line_prefix": REQUEST_LINE_PREFIX,
    },
    "sub_gate_a_predicate": (
        "07-env-after-fix.envNames contains 'APPLICATIONINSIGHTS_CONNECTION_STRING' "
        "AND 07-env-after-fix.image endswith ':v3' AND 07-env-after-fix.containerName "
        "== 'app' (BOTH-not-OR across all three conditions). Single-path. "
        "Record-scoped: parsed JSON membership + endswith + equality checks. The "
        "containerName check pins the env var to the SAME container the before-fix "
        "capture (Gate 17 sub-gate (a)) anchored on, not a sibling container that a "
        "parallel template change might have introduced."
    ),
    "sub_gate_b_predicate": (
        "09-ai-requests-after-fix.tables[0].rows has EXACTLY 1 element "
        "AND that element == ['unknown_service', 20] (BOTH-not-OR). "
        "Single-path. Record-scoped: parsed JSON array length + equality."
    ),
    "sub_gate_c_predicate": (
        "10-ai-traces-after-fix.tables[0].rows has EXACTLY 1 element "
        "AND that element == ['unknown_service', 21] (BOTH-not-OR). "
        "Single-path. Record-scoped."
    ),
    "sub_gate_d_predicate": (
        "13-ai-traces-messages-after-fix.tables[0].rows has EXACTLY 21 records "
        "AND EXACTLY 1 row's message column == 'Azure Monitor configured: telemetry "
        "export enabled' AND EXACTLY 20 rows' message column == '/ endpoint hit "
        "(conn_str_present=True)'. Single-path. Record-scoped iteration. Corroborates "
        "the aggregate count from sub-gate (c) by per-message breakdown."
    ),
    "sub_gate_e_predicate": (
        "00-verify-run.txt contains exactly 20 lines matching "
        "stripped.startswith('request ') AND 'HTTP 200' in stripped, "
        "AND contains the literal recovery PASS marker "
        "'PASS: After adding APPLICATIONINSIGHTS_CONNECTION_STRING', "
        "AND the file's total line count is exactly 111 "
        "(BOTH-not-OR across all three conditions). "
        "Line-scoped count + substring membership + length check. Single-path. "
        "The total-line-count check guards against truncated or augmented "
        "fix-and-capture logs that would still happen to contain 20 HTTP 200 "
        "lines and the recovery marker."
    ),
    "sub_gate_a_env_var_present_image_and_container_unchanged": {
        "observed_env_names": observed_env_names,
        "observed_image": observed_image,
        "observed_container_name": observed_container_name,
        "observed_env_present": a_env_present,
        "observed_image_ends_v3": a_image_ends_v3,
        "observed_container_name_is_app": a_container_name_is_app,
        "a_predicate_holds": a_predicate_holds,
        "a_pass": a_pass,
    },
    "sub_gate_b_ai_requests_exactly_one_unknown_service_20": {
        "observed_ai_requests_rows": ai_requests_rows,
        "observed_ai_requests_row_count": (
            len(ai_requests_rows) if isinstance(ai_requests_rows, list) else None
        ),
        "observed_rows_count_is_1": b_rows_count_is_1,
        "observed_first_row_matches_expected": b_first_row_matches,
        "expected_row": EXPECTED_REQUESTS_ROW,
        "b_predicate_holds": b_predicate_holds,
        "b_pass": b_pass,
    },
    "sub_gate_c_ai_traces_exactly_one_unknown_service_21": {
        "observed_ai_traces_rows": ai_traces_rows,
        "observed_ai_traces_row_count": (
            len(ai_traces_rows) if isinstance(ai_traces_rows, list) else None
        ),
        "observed_rows_count_is_1": c_rows_count_is_1,
        "observed_first_row_matches_expected": c_first_row_matches,
        "expected_row": EXPECTED_TRACES_ROW,
        "c_predicate_holds": c_predicate_holds,
        "c_pass": c_pass,
    },
    "sub_gate_d_per_message_corroboration_1_startup_plus_20_endpoint": {
        "observed_total_trace_records": observed_total_trace_records,
        "observed_startup_count": startup_count,
        "observed_endpoint_count": endpoint_count,
        "observed_message_column_index": message_column_index,
        "observed_total_count_is_21": d_total_count_is_21,
        "observed_startup_count_is_1": d_startup_count_is_1,
        "observed_endpoint_count_is_20": d_endpoint_count_is_20,
        "d_predicate_holds": d_predicate_holds,
        "d_pass": d_pass,
    },
    "sub_gate_e_verify_run_20_http_200_plus_recovery_pass_marker": {
        "observed_total_log_lines": e_observed_total_log_lines,
        "observed_http_200_count": e_observed_http_200_count,
        "observed_first_5_http_200_lines": verify_http_200_request_lines[:5],
        "observed_http_200_count_is_20": e_http_200_count_is_20,
        "observed_recovery_pass_marker_present": e_recovery_pass_marker_present,
        "observed_total_log_lines_matches": e_total_log_lines_matches,
        "e_predicate_holds": e_predicate_holds,
        "e_pass": e_pass,
    },
}
result["appinsights_h2_recovery_materialization_sub_gates"] = {
    "a_env_var_present_image_and_container_unchanged": result["sub_gate_a_env_var_present_image_and_container_unchanged"]["a_pass"],
    "b_ai_requests_exactly_one_unknown_service_20": result["sub_gate_b_ai_requests_exactly_one_unknown_service_20"]["b_pass"],
    "c_ai_traces_exactly_one_unknown_service_21": result["sub_gate_c_ai_traces_exactly_one_unknown_service_21"]["c_pass"],
    "d_per_message_corroboration_1_startup_plus_20_endpoint": result["sub_gate_d_per_message_corroboration_1_startup_plus_20_endpoint"]["d_pass"],
    "e_verify_run_20_http_200_plus_recovery_pass_marker": result["sub_gate_e_verify_run_20_http_200_plus_recovery_pass_marker"]["e_pass"],
}
result["appinsights_h2_recovery_materialization_all_subgates_pass"] = all(
    result["appinsights_h2_recovery_materialization_sub_gates"].values()
)
result["gate_classification"] = "adding_applicationinsights_connection_string_materialized_end_to_end_telemetry"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 19: single-variable falsification gate ==="
UTC_NOW="$UTC_NOW" \
CONFIG_BEFORE_FILE="$CONFIG_BEFORE_FILE" \
CONFIG_AFTER_FILE="$CONFIG_AFTER_FILE" \
REVISIONS_LIFECYCLE_FILE="$REVISIONS_LIFECYCLE_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE19_FILE"
import copy
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


config_before_path = pathlib.Path(os.environ["CONFIG_BEFORE_FILE"])
config_after_path = pathlib.Path(os.environ["CONFIG_AFTER_FILE"])
revisions_lifecycle_path = pathlib.Path(os.environ["REVISIONS_LIFECYCLE_FILE"])

config_before = json.loads(config_before_path.read_text())
config_after = json.loads(config_after_path.read_text())
revisions_lifecycle = json.loads(revisions_lifecycle_path.read_text())

EXPECTED_ENV_NAME = "APPLICATIONINSIGHTS_CONNECTION_STRING"
EXPECTED_IMAGE_SUFFIX = ":v3"
EXPECTED_CONTAINER_NAME = "app"
EXPECTED_BEFORE_REVISION_NAME_SUFFIX = "--0000006"
EXPECTED_AFTER_REVISION_NAME_SUFFIX = "--0000007"


def extract_first_container(config_root):
    """Return template.containers[0] dict, or None if path is broken.
    Record-scoped: parses the canonical Container Apps config schema."""
    properties = config_root.get("properties") or {}
    template = properties.get("template") or {}
    containers = template.get("containers") or []
    if not containers or not isinstance(containers, list):
        return None
    first = containers[0]
    return first if isinstance(first, dict) else None


def extract_registry_login_server(image_value):
    """Return the registry login server prefix (everything before the
    first '/') if the image value parses as a registry-qualified image
    reference; otherwise return None. Record-scoped: string parsing on
    a single parsed JSON field value, not whole-file grep."""
    if not isinstance(image_value, str):
        return None
    if "/" not in image_value:
        return None
    return image_value.split("/", 1)[0]


before_container = extract_first_container(config_before)
after_container = extract_first_container(config_after)

# Sub-gate (a): env-only delta. template.containers[0] of the before-fix
# and after-fix configs must be byte-identical when serialized with
# `sort_keys=True` AFTER removing the `env` key from both. Additionally,
# the before-fix env must be absent/null/empty, and the after-fix env
# must be a list of exactly 1 element whose .name ==
# APPLICATIONINSIGHTS_CONNECTION_STRING. Single-path BOTH-not-OR.
#
# Rationale for partial comparison: full-file byte comparison of the
# 05-/11- configs would falsely fail because the configs differ on
# unrelated systemData.lastModifiedAt timestamps, ingress.fqdn (which
# may be revision-suffixed), and latestRevisionName fields. The claim
# is specifically that template.containers[0] differs ONLY in env, so
# the predicate scopes to that subtree and removes env from both sides
# before comparison.
a_before_container_present = before_container is not None
a_after_container_present = after_container is not None
if a_before_container_present and a_after_container_present:
    before_no_env = copy.deepcopy(before_container)
    after_no_env = copy.deepcopy(after_container)
    before_no_env.pop("env", None)
    after_no_env.pop("env", None)
    before_serialized = json.dumps(before_no_env, sort_keys=True)
    after_serialized = json.dumps(after_no_env, sort_keys=True)
    a_container_byte_identical_after_removing_env = before_serialized == after_serialized
else:
    a_container_byte_identical_after_removing_env = False
    before_serialized = None
    after_serialized = None

before_env_field = before_container.get("env") if a_before_container_present else None
a_before_env_absent_or_empty = (
    before_env_field is None
    or (isinstance(before_env_field, list) and len(before_env_field) == 0)
)

after_env_field = after_container.get("env") if a_after_container_present else None
a_after_env_is_single_expected_var = False
if isinstance(after_env_field, list) and len(after_env_field) == 1:
    first_env_record = after_env_field[0]
    a_after_env_is_single_expected_var = (
        isinstance(first_env_record, dict)
        and first_env_record.get("name") == EXPECTED_ENV_NAME
    )

a_predicate_holds = (
    a_before_container_present
    and a_after_container_present
    and a_container_byte_identical_after_removing_env
    and a_before_env_absent_or_empty
    and a_after_env_is_single_expected_var
)
a_pass = a_predicate_holds

# Sub-gate (b): falsification pair anchored in 14-revisions-lifecycle.json.
# There must exist a record with name endswith "--0000006" AND image
# endswith ":v3" AND hasConnStr is False (the pre-fix pair member), AND
# a record with name endswith "--0000007" AND image endswith ":v3" AND
# hasConnStr is True AND active is True (the post-fix pair member).
# Single-path BOTH-not-OR per record. Record-scoped iteration on
# parsed JSON array.
before_pair_records = []
after_pair_records = []
if isinstance(revisions_lifecycle, list):
    for record in revisions_lifecycle:
        if not isinstance(record, dict):
            continue
        record_name = record.get("name")
        record_image = record.get("image")
        record_has_conn_str = record.get("hasConnStr")
        record_active = record.get("active")
        if (
            isinstance(record_name, str)
            and record_name.endswith(EXPECTED_BEFORE_REVISION_NAME_SUFFIX)
            and isinstance(record_image, str)
            and record_image.endswith(EXPECTED_IMAGE_SUFFIX)
            and record_has_conn_str is False
        ):
            before_pair_records.append(record)
        if (
            isinstance(record_name, str)
            and record_name.endswith(EXPECTED_AFTER_REVISION_NAME_SUFFIX)
            and isinstance(record_image, str)
            and record_image.endswith(EXPECTED_IMAGE_SUFFIX)
            and record_has_conn_str is True
            and record_active is True
        ):
            after_pair_records.append(record)
b_before_pair_present = len(before_pair_records) >= 1
b_after_pair_present = len(after_pair_records) >= 1
b_predicate_holds = b_before_pair_present and b_after_pair_present
b_pass = b_predicate_holds

# Sub-gate (c): same ACR registry prefix and same "app" container name
# across the before/after pair. Single-path BOTH-not-OR. Record-scoped:
# parses .image field of each container record and splits on '/' to
# extract registry prefix. Per Lab 21 lesson: registry identity is
# explicit in the parsed .image field so the same-registry proof is
# sound without requiring resource-id introspection.
before_image = before_container.get("image") if a_before_container_present else None
after_image = after_container.get("image") if a_after_container_present else None
before_registry = extract_registry_login_server(before_image)
after_registry = extract_registry_login_server(after_image)
before_container_name = (
    before_container.get("name") if a_before_container_present else None
)
after_container_name = (
    after_container.get("name") if a_after_container_present else None
)
c_same_registry = (
    isinstance(before_registry, str)
    and isinstance(after_registry, str)
    and before_registry == after_registry
)
c_same_container_name_app = (
    before_container_name == EXPECTED_CONTAINER_NAME
    and after_container_name == EXPECTED_CONTAINER_NAME
)
c_predicate_holds = c_same_registry and c_same_container_name_app
c_pass = c_predicate_holds

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "appinsights_connection_string_missing",
    "hypothesis": "H3_single_variable_falsification",
    "claim": "recovery_is_in_place_single_env_var_delta_same_image_container_registry",
    "claim_level": "Observed",
    "predicate_inputs": {
        "config_before_path": repo_rel(config_before_path),
        "config_after_path": repo_rel(config_after_path),
        "revisions_lifecycle_path": repo_rel(revisions_lifecycle_path),
    },
    "thresholds": {
        "expected_env_name": EXPECTED_ENV_NAME,
        "expected_image_suffix": EXPECTED_IMAGE_SUFFIX,
        "expected_container_name": EXPECTED_CONTAINER_NAME,
        "expected_before_revision_name_suffix": EXPECTED_BEFORE_REVISION_NAME_SUFFIX,
        "expected_after_revision_name_suffix": EXPECTED_AFTER_REVISION_NAME_SUFFIX,
    },
    "sub_gate_a_predicate": (
        "template.containers[0] of 05-containerapp-full-config-before-fix and "
        "11-containerapp-full-config-after-fix are byte-identical when serialized "
        "with sort_keys=True AFTER removing the 'env' key from both, AND the "
        "before-fix env is absent/null/empty, AND the after-fix env is a list of "
        "exactly 1 element whose .name == 'APPLICATIONINSIGHTS_CONNECTION_STRING'. "
        "Single-path BOTH-not-OR across all conditions. NOT a whole-file byte "
        "comparison — that would falsely fail on unrelated systemData.lastModifiedAt "
        "timestamps and revision-suffixed FQDNs."
    ),
    "sub_gate_b_predicate": (
        "14-revisions-lifecycle.json contains a record with .name endswith "
        "'--0000006' AND .image endswith ':v3' AND .hasConnStr is False (pre-fix "
        "pair member), AND a record with .name endswith '--0000007' AND .image "
        "endswith ':v3' AND .hasConnStr is True AND .active is True (post-fix "
        "pair member). Single-path BOTH-not-OR per record. Record-scoped."
    ),
    "sub_gate_c_predicate": (
        "Same ACR registry login server prefix (everything before first '/') in "
        "template.containers[0].image of before/after configs, AND both "
        "template.containers[0].name == 'app' (BOTH-not-OR). Single-path. "
        "Record-scoped: parses .image and .name fields, splits image on '/' "
        "to extract registry prefix."
    ),
    "sub_gate_a_env_only_delta_byte_identical_otherwise": {
        "observed_before_container_present": a_before_container_present,
        "observed_after_container_present": a_after_container_present,
        "observed_before_container_serialized_without_env": before_serialized,
        "observed_after_container_serialized_without_env": after_serialized,
        "observed_container_byte_identical_after_removing_env": a_container_byte_identical_after_removing_env,
        "observed_before_env_field": before_env_field,
        "observed_after_env_field_first_record_name": (
            after_env_field[0].get("name")
            if isinstance(after_env_field, list) and len(after_env_field) >= 1 and isinstance(after_env_field[0], dict)
            else None
        ),
        "observed_after_env_field_length": (
            len(after_env_field) if isinstance(after_env_field, list) else None
        ),
        "observed_before_env_absent_or_empty": a_before_env_absent_or_empty,
        "observed_after_env_is_single_expected_var": a_after_env_is_single_expected_var,
        "a_predicate_holds": a_predicate_holds,
        "a_pass": a_pass,
    },
    "sub_gate_b_falsification_pair_in_revisions_lifecycle": {
        "observed_before_pair_record_count": len(before_pair_records),
        "observed_before_pair_first_record": (
            before_pair_records[0] if before_pair_records else None
        ),
        "observed_after_pair_record_count": len(after_pair_records),
        "observed_after_pair_first_record": (
            after_pair_records[0] if after_pair_records else None
        ),
        "observed_before_pair_present": b_before_pair_present,
        "observed_after_pair_present": b_after_pair_present,
        "b_predicate_holds": b_predicate_holds,
        "b_pass": b_pass,
    },
    "sub_gate_c_same_registry_same_container_name": {
        "observed_before_image": before_image,
        "observed_after_image": after_image,
        "observed_before_registry": before_registry,
        "observed_after_registry": after_registry,
        "observed_before_container_name": before_container_name,
        "observed_after_container_name": after_container_name,
        "observed_same_registry": c_same_registry,
        "observed_same_container_name_app": c_same_container_name_app,
        "c_predicate_holds": c_predicate_holds,
        "c_pass": c_pass,
    },
}
result["appinsights_h3_single_variable_falsification_sub_gates"] = {
    "a_env_only_delta_byte_identical_otherwise": result["sub_gate_a_env_only_delta_byte_identical_otherwise"]["a_pass"],
    "b_falsification_pair_in_revisions_lifecycle": result["sub_gate_b_falsification_pair_in_revisions_lifecycle"]["b_pass"],
    "c_same_registry_same_container_name": result["sub_gate_c_same_registry_same_container_name"]["c_pass"],
}
result["appinsights_h3_single_variable_falsification_all_subgates_pass"] = all(
    result["appinsights_h3_single_variable_falsification_sub_gates"].values()
)
result["gate_classification"] = "recovery_is_in_place_single_env_var_delta_same_image_container_registry"
print(json.dumps(result, indent=2))
PY

echo "=== Phase summary ==="
GATE16_FILE="$GATE16_FILE" \
GATE17_FILE="$GATE17_FILE" \
GATE18_FILE="$GATE18_FILE" \
GATE19_FILE="$GATE19_FILE" \
python3 <<'PY'
import json
import os
import pathlib
import sys

gates = [
    (
        "16",
        "cohort_integrity",
        pathlib.Path(os.environ["GATE16_FILE"]),
        "appinsights_h_cohort_integrity_sub_gates",
        "appinsights_h_cohort_integrity_all_subgates_pass",
    ),
    (
        "17",
        "failure_attribution",
        pathlib.Path(os.environ["GATE17_FILE"]),
        "appinsights_h1_failure_attribution_sub_gates",
        "appinsights_h1_failure_attribution_all_subgates_pass",
    ),
    (
        "18",
        "recovery_materialization",
        pathlib.Path(os.environ["GATE18_FILE"]),
        "appinsights_h2_recovery_materialization_sub_gates",
        "appinsights_h2_recovery_materialization_all_subgates_pass",
    ),
    (
        "19",
        "single_variable_falsification",
        pathlib.Path(os.environ["GATE19_FILE"]),
        "appinsights_h3_single_variable_falsification_sub_gates",
        "appinsights_h3_single_variable_falsification_all_subgates_pass",
    ),
]

overall = True
print("gate | name                           | sub-gates                                                                                  | overall")
print("-----|--------------------------------|--------------------------------------------------------------------------------------------|--------")
for gate_id, name, path, sub_key, overall_key in gates:
    data = json.loads(path.read_text())
    subs = data[sub_key]
    sub_summary = ", ".join(f"{k}={'PASS' if v else 'FAIL'}" for k, v in subs.items())
    gate_pass = bool(data[overall_key])
    overall = overall and gate_pass
    print(f"{gate_id:>4} | {name:<30} | {sub_summary:<90} | {'PASS' if gate_pass else 'FAIL'}")

print("")
print(f"overall_phase_b_verdict={'PASS' if overall else 'FAIL'}")
sys.exit(0 if overall else 1)
PY
