#!/usr/bin/env bash
# verify.sh — Phase B evidence-pack verification for Lab 20
# (revision-history-limit).
#
# File purpose
# ------------
# Phase B verify.sh — pure file processor — emits 4 falsifiable gate JSONs
# from committed canonical evidence. This script reads ONLY the canonical
# 00-/01-/.../10- evidence files already checked into
# `labs/revision-history-limit/evidence/` and writes the derived gate
# outputs:
#
#   - 20-cohort-integrity-gate.json
#   - 21-config-persistence-gate.json
#   - 22-burst-materialization-gate.json
#   - 23-bounded-window-non-pruning-gate.json
#
# It MUST NOT call Azure, curl remote endpoints, or depend on any live cloud
# state. A reviewer must be able to re-run this script after the lab RG has
# been deleted and still obtain the same verdict from the same committed
# evidence.
#
# Oracle ses_1069d765dffezi1iYs4KKtHH6r directives (verbatim, binding)
# -------------------------------------------------------------------
#   "Best next pick because the evidence pack is small but complete"
#   "Four falsifiable gates: cohort integrity, config persistence, burst
#    materialization, bounded-window non-pruning"
#   "Keep the headline to 'pruning was not prompt within this 15-minute
#    observation window in this reproduction.' Do not generalize to
#    platform-wide timing guarantees"
#   "Use the burst timestamp already committed in evidence and normalize it
#    to an identifier like burst-20260622-080146"
#   "Allow a lower floor such as >=8 if you want rerun tolerance for the
#    burst-materialization gate"
#
# Numbered prefix policy
# ----------------------
# 00-/01-/.../10- = canonical committed evidence inputs (Phase A outputs).
# 20-/21-/22-/23- = derived Phase B gate outputs generated by this script.
#
# The 20-23 prefix is intentional — it avoids collision with the canonical
# 10-deployment-outputs.json file that Phase A already wrote. If this script
# used 10-13 (as labs 18 and 19 do), the Gate 10 JSON would overwrite the
# canonical 10-deployment-outputs.json artifact and orphan the evidence.
#
# What the four gates prove
# -------------------------
# Gate 20 = cohort integrity gate.
#   Claim: the canonical evidence pack is internally coherent before any
#   hypothesis reasoning starts. This gate consumes the 14 canonical files
#   but reasons about presence, anchor agreement, no-extras, and README
#   cross-reference only.
#
# Gate 21 = config persistence gate.
#   Claim: the configured maxInactiveRevisions=2 + activeRevisionsMode=Single
#   was honored by the platform across the entire 15-minute observation
#   window. The pre-burst config readback (01-app-config-before.json) and
#   the post-window config readback (06-app-config-t15m.json) both show the
#   identical configured values. This is the H1 falsification check.
#
# Gate 22 = burst materialization gate.
#   Claim: the trigger.sh burst phase genuinely produced a new revision per
#   env-var-only update. The initial baseline shows 1 revision, the
#   immediate post-burst snapshot shows 11 revisions (1 original + 10 burst
#   children) with 11 distinct names. The strong path holds the canonical
#   2026-06-22 reproduction at exactly 11; the fallback path tolerates
#   future re-captures down to a floor of 8 (Oracle directive).
#
# Gate 23 = bounded-window non-pruning gate.
#   Claim: pruning was NOT prompt within the 15-minute observation window
#   in this reproduction. Inactive revision counts at t+5m AND t+15m are
#   both > 2 (the configured maxInactiveRevisions target). This is the H2
#   falsification check.
#
#   BOTH-NOT-OR semantics (Lab 19 P0 lesson): the gate requires BOTH the
#   t+5m snapshot AND the t+15m snapshot to show inactive > 2, not just
#   either-or. The bounded-observation claim depends on the full window,
#   not a single time slice. The gate also requires monotonic non-decrease
#   (t+15m inactive count >= t+5m inactive count) to prove pruning did not
#   start partway through the window.
#
# Gate topology
# -------------
# 4 top-level gates with 12 sub-gates total:
#
#   Gate 20 (H_cohort_integrity) — 4 sub-gates
#     a) all 14 canonical files exist
#     b) anchor agreement (epoch file ↔ ISO file are reciprocal)
#     c) no unexpected non-junk extras (exact-match strong, junk-tolerant fallback)
#     d) README.md cross-references all 4 Phase B gate JSON filenames
#
#   Gate 21 (H1_config_persistence) — 2 sub-gates
#     a) pre-burst config shows maxInactiveRevisions=2 AND mode=Single
#     b) post-window config shows the same BOTH-not-OR AND is byte-identical
#        to the pre-burst config
#
#   Gate 22 (H_burst_materialization) — 3 sub-gates
#     a) initial baseline (02-revisions-initial.json) has exactly 1 revision
#        (strong AND fallback both enforce == 1 per Oracle PR #279 P0-4;
#         dual-path retained for JSON schema parity, not semantic relaxation)
#     b) post-burst snapshot (03-revisions-t0.json) has exactly 11 revisions
#        (strong) / >= 8 (fallback per Oracle directive)
#     c) post-burst snapshot has 11 distinct revision names (strong) / >= 8
#        distinct names (fallback)
#
#   Gate 23 (H2_bounded_window_non_pruning) — 3 sub-gates
#     a) t+5m inactive count > 2 (strong: >= 8) / > 2 (fallback)
#     b) t+15m inactive count > 2 (strong: >= 8) / > 2 (fallback)
#     c) BOTH t+5m AND t+15m show inactive > 2 AND t+15m >= t+5m
#        (monotonic non-decrease)
#
# Verdict semantics encoded by this script
# ---------------------------------------
# Gate 20 PASS = the evidence cohort is internally consistent.
# Gate 21 PASS = the configured maxInactiveRevisions=2 was honored across
#   the entire observation window (H1 not falsified).
# Gate 22 PASS = the trigger.sh burst genuinely created new revisions
#   (proves the experiment ran; not a no-op).
# Gate 23 PASS = pruning was NOT prompt within the 15-min window in this
#   reproduction (H2 not falsified — bounded-observation claim supported).
#
# Gate 21 + Gate 23 together encode: maxInactiveRevisions is a TARGET, not
# a 15-min SLA. Operators relying on this preview setting for deterministic
# short-window cleanup will be disappointed; explicit
# `az containerapp revision deactivate` is the deterministic alternative.
#
# Claim ceiling (strict, Oracle directive)
# ----------------------------------------
# The supported claim from this evidence is:
#   "Pruning was not prompt within this 15-minute observation window in
#    this reproduction."
# NOT:
#   "Pruning never happens within 15 minutes."
#   "Pruning interval is N minutes."
#   "The platform guarantees X."
# The 15-minute observation window is short relative to the platform's
# undocumented pruning cadence. A single reproduction cannot characterize
# the long-run distribution.
#
# QUOTED heredoc rule (mandatory)
# -------------------------------
# ALL Python heredocs in this file MUST use `<<'PY'` (single-quoted
# delimiter) to prevent shell expansion of `$` characters inside Python
# code. This is a Lab 14 lesson 29 mandatory rule. Unquoted `<<PY` would
# cause `$variable` in Python to be silently replaced by bash before the
# heredoc reaches python3.
#
# REPO_RELATIVE_EVIDENCE_DIR rule (mandatory)
# -------------------------------------------
# All gate JSONs MUST cite predicate inputs as repo-relative paths (for
# example `labs/revision-history-limit/evidence/01-app-config-before.json`),
# NOT absolute paths. This prevents `/Users/<alias>/...` leakage into
# committed evidence and keeps the pack reproducible across operator
# machines.
#
# Record-scoped predicate rule (mandatory)
# ----------------------------------------
# Lab 15 lesson 34 — no whole-file substring searches. Every assertion must
# come from parsed records. This script uses Python `json.load()` plus
# record iteration ONLY. It never greps the canonical JSON files to count
# matches. Every strong/fallback predicate is evaluated from typed record
# fields.
#
# BOTH-not-OR rule (Lab 19 P0 lesson, applied to Gate 23)
# -------------------------------------------------------
# Where the hypothesis claim is about BOTH endpoints of an interval, the
# gate predicate must use AND (not OR) between the endpoints. Gate 23
# claims "pruning was not prompt across the 15-minute window" — that
# requires inactive > 2 at BOTH t+5m AND t+15m, plus monotonic
# non-decrease between them, not just at either endpoint.
#
# Canonical evidence consumed by this script
# ------------------------------------------
# Gate 20 consumes:
#   ALL 14 canonical files (presence + anchor + extras + README)
#
# Gate 21 consumes:
#   01-app-config-before.json (pre-burst config readback)
#   06-app-config-t15m.json   (post-window config readback)
#
# Gate 22 consumes:
#   02-revisions-initial.json (pre-burst revision list)
#   03-revisions-t0.json      (immediate post-burst revision list)
#
# Gate 23 consumes:
#   04-revisions-t5m.json   (revision list at burst+5m)
#   05-revisions-t15m.json  (revision list at burst+15m)
#
# Files explicitly NOT consumed by this script
# --------------------------------------------
# These canonical files are part of the cohort (Gate 20 checks their
# presence) but are NOT used as predicate inputs by Gates 21-23:
#   - 00-trigger-run.txt          (Phase A trigger.sh stdout, human-readable)
#   - 00-verify-run.txt           (Phase A capture-window.sh stdout, human-readable)
#   - 07-cli-versions.json        (operator environment metadata)
#   - 08-cli-containerapp-ext.json (operator environment metadata)
#   - 09-region.json              (region metadata)
#   - 10-deployment-outputs.json  (Bicep deployment outputs)
#   - burst-completed-epoch.txt   (used only by Gate 20 anchor check, not Gates 22-23)
#   - burst-completed-iso.txt     (used only by Gate 20 anchor check, not Gates 22-23)
#
# Usage
# -----
#   bash labs/revision-history-limit/verify.sh
#
# No environment variables are required.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_DIR="$SCRIPT_DIR"
EVIDENCE_DIR="$LAB_DIR/evidence"
REPO_RELATIVE_EVIDENCE_DIR="labs/revision-history-limit/evidence"
UTC_NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Canonical input files (Phase A outputs).
TRIGGER_LOG_FILE="$EVIDENCE_DIR/00-trigger-run.txt"
CAPTURE_LOG_FILE="$EVIDENCE_DIR/00-verify-run.txt"
CONFIG_BEFORE_FILE="$EVIDENCE_DIR/01-app-config-before.json"
REVS_INITIAL_FILE="$EVIDENCE_DIR/02-revisions-initial.json"
REVS_T0_FILE="$EVIDENCE_DIR/03-revisions-t0.json"
REVS_T5M_FILE="$EVIDENCE_DIR/04-revisions-t5m.json"
REVS_T15M_FILE="$EVIDENCE_DIR/05-revisions-t15m.json"
CONFIG_T15M_FILE="$EVIDENCE_DIR/06-app-config-t15m.json"
CLI_VERSIONS_FILE="$EVIDENCE_DIR/07-cli-versions.json"
CLI_EXT_FILE="$EVIDENCE_DIR/08-cli-containerapp-ext.json"
REGION_FILE="$EVIDENCE_DIR/09-region.json"
DEPLOYMENT_OUTPUTS_FILE="$EVIDENCE_DIR/10-deployment-outputs.json"
BURST_EPOCH_FILE="$EVIDENCE_DIR/burst-completed-epoch.txt"
BURST_ISO_FILE="$EVIDENCE_DIR/burst-completed-iso.txt"

# Phase B gate output files (20-23 prefix avoids collision with
# 10-deployment-outputs.json canonical file).
GATE20_FILE="$EVIDENCE_DIR/20-cohort-integrity-gate.json"
GATE21_FILE="$EVIDENCE_DIR/21-config-persistence-gate.json"
GATE22_FILE="$EVIDENCE_DIR/22-burst-materialization-gate.json"
GATE23_FILE="$EVIDENCE_DIR/23-bounded-window-non-pruning-gate.json"

for required in \
    "$TRIGGER_LOG_FILE" \
    "$CAPTURE_LOG_FILE" \
    "$CONFIG_BEFORE_FILE" \
    "$REVS_INITIAL_FILE" \
    "$REVS_T0_FILE" \
    "$REVS_T5M_FILE" \
    "$REVS_T15M_FILE" \
    "$CONFIG_T15M_FILE" \
    "$CLI_VERSIONS_FILE" \
    "$CLI_EXT_FILE" \
    "$REGION_FILE" \
    "$DEPLOYMENT_OUTPUTS_FILE" \
    "$BURST_EPOCH_FILE" \
    "$BURST_ISO_FILE"; do
    if [[ ! -f "$required" ]]; then
        echo "ERROR: required canonical evidence file missing: $required" >&2
        echo "This Phase B verify.sh is a pure file processor and cannot synthesize missing evidence." >&2
        exit 1
    fi
done

echo "=== Phase 20: cohort integrity gate ==="
UTC_NOW="$UTC_NOW" \
EVIDENCE_DIR="$EVIDENCE_DIR" \
TRIGGER_LOG_FILE="$TRIGGER_LOG_FILE" \
CAPTURE_LOG_FILE="$CAPTURE_LOG_FILE" \
CONFIG_BEFORE_FILE="$CONFIG_BEFORE_FILE" \
REVS_INITIAL_FILE="$REVS_INITIAL_FILE" \
REVS_T0_FILE="$REVS_T0_FILE" \
REVS_T5M_FILE="$REVS_T5M_FILE" \
REVS_T15M_FILE="$REVS_T15M_FILE" \
CONFIG_T15M_FILE="$CONFIG_T15M_FILE" \
CLI_VERSIONS_FILE="$CLI_VERSIONS_FILE" \
CLI_EXT_FILE="$CLI_EXT_FILE" \
REGION_FILE="$REGION_FILE" \
DEPLOYMENT_OUTPUTS_FILE="$DEPLOYMENT_OUTPUTS_FILE" \
BURST_EPOCH_FILE="$BURST_EPOCH_FILE" \
BURST_ISO_FILE="$BURST_ISO_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE20_FILE"
import json
import os
import pathlib
from datetime import datetime, timezone


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


def sample(items, n=5):
    return items[:n]


canonical_paths = [
    pathlib.Path(os.environ["TRIGGER_LOG_FILE"]),
    pathlib.Path(os.environ["CAPTURE_LOG_FILE"]),
    pathlib.Path(os.environ["CONFIG_BEFORE_FILE"]),
    pathlib.Path(os.environ["REVS_INITIAL_FILE"]),
    pathlib.Path(os.environ["REVS_T0_FILE"]),
    pathlib.Path(os.environ["REVS_T5M_FILE"]),
    pathlib.Path(os.environ["REVS_T15M_FILE"]),
    pathlib.Path(os.environ["CONFIG_T15M_FILE"]),
    pathlib.Path(os.environ["CLI_VERSIONS_FILE"]),
    pathlib.Path(os.environ["CLI_EXT_FILE"]),
    pathlib.Path(os.environ["REGION_FILE"]),
    pathlib.Path(os.environ["DEPLOYMENT_OUTPUTS_FILE"]),
    pathlib.Path(os.environ["BURST_EPOCH_FILE"]),
    pathlib.Path(os.environ["BURST_ISO_FILE"]),
]
evidence_dir = pathlib.Path(os.environ["EVIDENCE_DIR"])
burst_epoch_path = pathlib.Path(os.environ["BURST_EPOCH_FILE"])
burst_iso_path = pathlib.Path(os.environ["BURST_ISO_FILE"])

# Sub-gate (a): all 14 canonical files exist.
presence_records = [{"path": repo_rel(p), "exists": p.exists()} for p in canonical_paths]
present_count = sum(1 for item in presence_records if item["exists"])
a_strong_path_all_14_files_exist = present_count == 14
a_fallback_path_at_least_12_files_exist = present_count >= 12
a_pass = a_strong_path_all_14_files_exist or a_fallback_path_at_least_12_files_exist

# Sub-gate (b): anchor agreement. The two anchor files MUST reciprocate —
# int(epoch_file) converted to ISO 8601 UTC must match the contents of
# iso_file (after stripping trailing whitespace). The fallback path
# preserves the SAME intent (anchor agreement) by tolerating up to 2 s
# drift between the parsed epoch and the parsed ISO timestamp.
# Oracle PR #279 P0-2 lesson — the fallback MUST NOT relax to "both
# files parseable" because that allows arbitrary clock drift (hours,
# days) to pass, which weakens the documented contract in §4b Gate 20
# row ("Fallback path: within ±2 s drift").
b_anchor_records = {}
b_strong_path_anchor_files_reciprocal = False
b_fallback_path_anchor_drift_within_2s = False
try:
    epoch_raw = burst_epoch_path.read_text().strip()
    iso_raw = burst_iso_path.read_text().strip()
    epoch_int = int(epoch_raw)
    iso_from_epoch = datetime.fromtimestamp(epoch_int, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    b_anchor_records = {
        "epoch_file_path": repo_rel(burst_epoch_path),
        "iso_file_path": repo_rel(burst_iso_path),
        "epoch_value": epoch_int,
        "iso_from_epoch_derivation": iso_from_epoch,
        "iso_file_content": iso_raw,
        "anchor_basename": f"burst-{datetime.fromtimestamp(epoch_int, tz=timezone.utc).strftime('%Y%m%d-%H%M%S')}",
    }
    b_strong_path_anchor_files_reciprocal = iso_from_epoch == iso_raw
    # Fallback path: tolerate ≤2 s drift between the two anchor sources.
    try:
        iso_parsed = datetime.strptime(iso_raw, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        epoch_dt = datetime.fromtimestamp(epoch_int, tz=timezone.utc)
        drift_seconds = abs((iso_parsed - epoch_dt).total_seconds())
        b_anchor_records["drift_seconds"] = drift_seconds
        b_anchor_records["drift_tolerance_seconds"] = 2
        b_fallback_path_anchor_drift_within_2s = drift_seconds <= 2
    except ValueError as iso_exc:
        b_anchor_records["fallback_iso_parse_error"] = str(iso_exc)
        b_fallback_path_anchor_drift_within_2s = False
except (ValueError, OSError) as exc:
    b_anchor_records = {
        "epoch_file_path": repo_rel(burst_epoch_path),
        "iso_file_path": repo_rel(burst_iso_path),
        "parse_error": str(exc),
    }
b_pass = b_strong_path_anchor_files_reciprocal or b_fallback_path_anchor_drift_within_2s

# Sub-gate (c): no unexpected non-junk extras. Lab 19 P0 lesson — the
# fallback path must REJECT any non-junk extras, not just check for junk
# patterns. Phase B outputs (20-23 gate JSONs) and README.md are expected
# and excluded; everything else outside the canonical 14 is an unexpected
# extra unless it matches the allowed-junk pattern.
canonical_names = {p.name for p in canonical_paths}
phase_b_outputs = {
    "20-cohort-integrity-gate.json",
    "21-config-persistence-gate.json",
    "22-burst-materialization-gate.json",
    "23-bounded-window-non-pruning-gate.json",
}
expected_meta = {"README.md"}
actual_names = {p.name for p in evidence_dir.iterdir() if p.is_file()}
extras_found = sorted(actual_names - canonical_names - phase_b_outputs - expected_meta)
missing_canonical = sorted(canonical_names - actual_names)

ALLOWED_JUNK_SUFFIXES = (".swp", ".bak", ".tmp")
ALLOWED_JUNK_EXACT_NAMES = (".DS_Store",)


def is_allowed_junk(name):
    return (
        name in ALLOWED_JUNK_EXACT_NAMES
        or any(name.endswith(suffix) for suffix in ALLOWED_JUNK_SUFFIXES)
    )


unexpected_non_junk_extras = [f for f in extras_found if not is_allowed_junk(f)]
c_strong_path_exact_match = len(extras_found) == 0 and len(missing_canonical) == 0
c_fallback_path_no_foreign_files = (
    len(missing_canonical) == 0 and len(unexpected_non_junk_extras) == 0
)
c_pass = c_strong_path_exact_match or c_fallback_path_no_foreign_files

# Sub-gate (d): README.md cross-references all 4 Phase B gate JSON filenames.
# Strong path requires the README to mention every gate JSON by exact name;
# fallback path requires the README file to exist (so a future maintainer
# at least has a starting point for the provenance trail).
readme_path = evidence_dir / "README.md"
d_readme_exists = readme_path.exists()
d_strong_path_readme_references_all_gates = False
d_fallback_path_readme_exists = d_readme_exists
gate_reference_records = []
if d_readme_exists:
    readme_text = readme_path.read_text()
    gate_reference_records = [
        {"gate_filename": gate_name, "mentioned_in_readme": gate_name in readme_text}
        for gate_name in sorted(phase_b_outputs)
    ]
    d_strong_path_readme_references_all_gates = all(
        item["mentioned_in_readme"] for item in gate_reference_records
    )
d_pass = d_strong_path_readme_references_all_gates or d_fallback_path_readme_exists

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "revision_history_limit_bounded_observation",
    "hypothesis": "H_cohort_integrity",
    "claim": "evidence_cohort_is_internally_consistent_and_uncontaminated",
    "claim_level": "Observed",
    "predicate_inputs": {
        "evidence_dir": os.environ["REPO_RELATIVE_EVIDENCE_DIR"],
        "canonical_files_manifest": sorted(canonical_names),
        "phase_b_outputs_manifest": sorted(phase_b_outputs),
        "expected_meta_files": sorted(expected_meta),
    },
    "sub_gate_a_predicate": (
        "All 14 canonical Phase A files exist; fallback requires at least 12."
    ),
    "sub_gate_b_predicate": (
        "burst-completed-epoch.txt and burst-completed-iso.txt are reciprocal "
        "(int(epoch) → ISO matches ISO file contents); fallback requires "
        "anchor agreement within ≤2 s drift between the parsed epoch and "
        "the parsed ISO timestamp (NOT mere parseability)."
    ),
    "sub_gate_c_predicate": (
        "No unexpected non-junk extras under evidence/. Strong path requires exact match "
        "of the canonical 14 + 4 Phase B outputs + README.md; fallback tolerates only "
        "editor/OS junk (.swp/.bak/.tmp/.DS_Store) and STILL requires zero missing canonical files."
    ),
    "sub_gate_d_predicate": (
        "evidence/README.md cross-references all 4 Phase B gate JSON filenames; "
        "fallback requires only that README.md exists."
    ),
    "required_canonical_file_count": 14,
    "minimum_fallback_file_count": 12,
    "sub_gate_a_canonical_files_present": {
        "observed_present_file_count": present_count,
        "observed_first_5": sample(presence_records),
        "a_strong_path_all_14_files_exist": a_strong_path_all_14_files_exist,
        "a_fallback_path_at_least_12_files_exist": a_fallback_path_at_least_12_files_exist,
        "a_pass": a_pass,
    },
    "sub_gate_b_anchor_files_reciprocal": {
        "observed_anchor_records": b_anchor_records,
        "b_strong_path_anchor_files_reciprocal": b_strong_path_anchor_files_reciprocal,
        "b_fallback_path_anchor_drift_within_2s": b_fallback_path_anchor_drift_within_2s,
        "b_pass": b_pass,
    },
    "sub_gate_c_no_unexpected_extras": {
        "observed_extras_count": len(extras_found),
        "observed_extras": extras_found,
        "observed_missing_canonical": missing_canonical,
        "unexpected_non_junk_extras": unexpected_non_junk_extras,
        "allowed_junk_suffixes": list(ALLOWED_JUNK_SUFFIXES),
        "allowed_junk_exact_names": list(ALLOWED_JUNK_EXACT_NAMES),
        "c_strong_path_exact_match": c_strong_path_exact_match,
        "c_fallback_path_no_foreign_files": c_fallback_path_no_foreign_files,
        "c_pass": c_pass,
    },
    "sub_gate_d_readme_references_gate_outputs": {
        "observed_readme_exists": d_readme_exists,
        "observed_gate_reference_records": gate_reference_records,
        "d_strong_path_readme_references_all_gates": d_strong_path_readme_references_all_gates,
        "d_fallback_path_readme_exists": d_fallback_path_readme_exists,
        "d_pass": d_pass,
    },
}
result["revision_history_limit_h_cohort_integrity_sub_gates"] = {
    "a_canonical_files_present": result["sub_gate_a_canonical_files_present"]["a_pass"],
    "b_anchor_files_reciprocal": result["sub_gate_b_anchor_files_reciprocal"]["b_pass"],
    "c_no_unexpected_extras": result["sub_gate_c_no_unexpected_extras"]["c_pass"],
    "d_readme_references_gate_outputs": result["sub_gate_d_readme_references_gate_outputs"]["d_pass"],
}
result["revision_history_limit_h_cohort_integrity_all_subgates_pass"] = all(
    result["revision_history_limit_h_cohort_integrity_sub_gates"].values()
)
result["gate_classification"] = "evidence_cohort_is_internally_consistent_and_uncontaminated"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 21: config persistence gate ==="
UTC_NOW="$UTC_NOW" \
CONFIG_BEFORE_FILE="$CONFIG_BEFORE_FILE" \
CONFIG_T15M_FILE="$CONFIG_T15M_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE21_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


config_before_path = pathlib.Path(os.environ["CONFIG_BEFORE_FILE"])
config_t15m_path = pathlib.Path(os.environ["CONFIG_T15M_FILE"])

config_before_raw = config_before_path.read_text()
config_t15m_raw = config_t15m_path.read_text()
config_before = json.loads(config_before_raw)
config_t15m = json.loads(config_t15m_raw)

EXPECTED_MAX_INACTIVE = 2
EXPECTED_MODE = "Single"

# Sub-gate (a): pre-burst config shows the expected configured values.
# Strong AND Fallback paths BOTH enforce {maxInactiveRevisions=2,
# activeRevisionsMode=Single} per Oracle PR #279 P0-3 directive.
# The fallback exists for schema parity with the gate JSON shape (every
# sub-gate has both paths emitted), NOT to weaken the contract. Earlier
# `isinstance(int) and >= 0` allowed any finite integer to pass — that
# would pass `maxInactiveRevisions=100` (the platform default), which
# means the operator could un-set the Bicep value and the gate would
# still report PASS. The fallback now mirrors the strong path.
before_max_inactive = config_before.get("maxInactiveRevisions")
before_mode = config_before.get("activeRevisionsMode")
a_strong_before_both_fields_match = (
    before_max_inactive == EXPECTED_MAX_INACTIVE and before_mode == EXPECTED_MODE
)
a_fallback_before_both_fields_match = (
    before_max_inactive == EXPECTED_MAX_INACTIVE and before_mode == EXPECTED_MODE
)
a_pass = a_strong_before_both_fields_match or a_fallback_before_both_fields_match

# Sub-gate (b): post-window config shows the same configured values
# (BOTH-not-OR: both fields must match) AND is byte-identical to the
# pre-burst config (proves the platform did not mutate the configured
# values mid-window).
t15m_max_inactive = config_t15m.get("maxInactiveRevisions")
t15m_mode = config_t15m.get("activeRevisionsMode")
t15m_both_fields_match = (
    t15m_max_inactive == EXPECTED_MAX_INACTIVE and t15m_mode == EXPECTED_MODE
)
byte_identical = config_before_raw == config_t15m_raw
b_strong_path_both_fields_match_and_byte_identical = t15m_both_fields_match and byte_identical
b_fallback_path_both_fields_match = t15m_both_fields_match
b_pass = b_strong_path_both_fields_match_and_byte_identical or b_fallback_path_both_fields_match

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "revision_history_limit_bounded_observation",
    "hypothesis": "H1_config_persistence",
    "claim": "max_inactive_revisions_target_honored_across_observation_window",
    "claim_level": "Observed",
    "predicate_inputs": {
        "config_before_path": repo_rel(config_before_path),
        "config_t15m_path": repo_rel(config_t15m_path),
    },
    "thresholds": {
        "expected_max_inactive_revisions": EXPECTED_MAX_INACTIVE,
        "expected_active_revisions_mode": EXPECTED_MODE,
    },
    "sub_gate_a_predicate": (
        "Pre-burst config readback (01-app-config-before.json) shows "
        "maxInactiveRevisions=2 AND activeRevisionsMode=Single. The "
        "fallback path enforces the SAME both-fields-match predicate "
        "(intent-preserving per Oracle PR #279 P0-3 directive — fallback "
        "must not weaken the documented contract; the dual-path shape "
        "exists for JSON schema parity, not for semantic relaxation)."
    ),
    "sub_gate_b_predicate": (
        "Post-window config readback (06-app-config-t15m.json) shows the same "
        "BOTH fields match (BOTH-not-OR per Lab 19 P0 lesson) AND the file is "
        "byte-identical to the pre-burst config (proves no mid-window mutation); "
        "fallback requires only that both fields match without byte-identity."
    ),
    "sub_gate_a_pre_burst_config_persisted": {
        "observed_before_max_inactive_revisions": before_max_inactive,
        "observed_before_active_revisions_mode": before_mode,
        "a_strong_path_both_fields_match_expected": a_strong_before_both_fields_match,
        "a_fallback_path_both_fields_match_expected": a_fallback_before_both_fields_match,
        "a_pass": a_pass,
    },
    "sub_gate_b_post_window_config_persisted": {
        "observed_t15m_max_inactive_revisions": t15m_max_inactive,
        "observed_t15m_active_revisions_mode": t15m_mode,
        "observed_byte_identical_to_pre_burst": byte_identical,
        "b_strong_path_both_fields_match_and_byte_identical": b_strong_path_both_fields_match_and_byte_identical,
        "b_fallback_path_both_fields_match": b_fallback_path_both_fields_match,
        "b_pass": b_pass,
    },
}
result["revision_history_limit_h1_config_persistence_sub_gates"] = {
    "a_pre_burst_config_persisted": result["sub_gate_a_pre_burst_config_persisted"]["a_pass"],
    "b_post_window_config_persisted": result["sub_gate_b_post_window_config_persisted"]["b_pass"],
}
result["revision_history_limit_h1_config_persistence_all_subgates_pass"] = all(
    result["revision_history_limit_h1_config_persistence_sub_gates"].values()
)
result["gate_classification"] = "max_inactive_revisions_target_honored_across_observation_window"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 22: burst materialization gate ==="
UTC_NOW="$UTC_NOW" \
REVS_INITIAL_FILE="$REVS_INITIAL_FILE" \
REVS_T0_FILE="$REVS_T0_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE22_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


def sample(items, n=5):
    return items[:n]


revs_initial_path = pathlib.Path(os.environ["REVS_INITIAL_FILE"])
revs_t0_path = pathlib.Path(os.environ["REVS_T0_FILE"])

revs_initial = json.loads(revs_initial_path.read_text())
revs_t0 = json.loads(revs_t0_path.read_text())

# Sub-gate (a): initial baseline has exactly 1 revision. Strong AND
# Fallback BOTH enforce initial_count == 1 per Oracle PR #279 P0-4
# directive — the fallback must NOT relax to `>= 1`, which would allow
# an already-burst app being re-used and would silently break the
# materialization gate's interpretation (the +10 burst-suffix check in
# sub-gates b and c assumes a 1-revision baseline). The fallback path
# exists for JSON schema parity, NOT for semantic relaxation.
initial_count = len(revs_initial)
a_strong_path_initial_exactly_one = initial_count == 1
a_fallback_path_initial_exactly_one = initial_count == 1
a_pass = a_strong_path_initial_exactly_one or a_fallback_path_initial_exactly_one

# Sub-gate (b): post-burst snapshot has exactly 11 revisions (strong)
# or at least 8 revisions (fallback per Oracle directive — tolerates
# minor variations in burst loop completion).
t0_count = len(revs_t0)
b_strong_path_t0_exactly_eleven = t0_count == 11
b_fallback_path_t0_at_least_eight = t0_count >= 8
b_pass = b_strong_path_t0_exactly_eleven or b_fallback_path_t0_at_least_eight

# Sub-gate (c): post-burst snapshot has 11 distinct revision names
# (strong) or at least 8 distinct names (fallback). This proves each
# env-var-only update materialized a NEW revision rather than reusing
# an existing one.
t0_names = [str(record.get("name", "")) for record in revs_t0 if record.get("name")]
distinct_t0_names = sorted(set(t0_names))
distinct_count = len(distinct_t0_names)
c_strong_path_distinct_exactly_eleven = distinct_count == 11
c_fallback_path_distinct_at_least_eight = distinct_count >= 8
c_pass = c_strong_path_distinct_exactly_eleven or c_fallback_path_distinct_at_least_eight

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "revision_history_limit_bounded_observation",
    "hypothesis": "H_burst_materialization",
    "claim": "env_var_only_updates_materialized_distinct_new_revisions",
    "claim_level": "Observed",
    "predicate_inputs": {
        "revs_initial_path": repo_rel(revs_initial_path),
        "revs_t0_path": repo_rel(revs_t0_path),
    },
    "thresholds": {
        "strong_initial_count": 1,
        "fallback_initial_count": 1,
        "strong_t0_count": 11,
        "fallback_t0_minimum": 8,
        "strong_distinct_t0_count": 11,
        "fallback_distinct_t0_minimum": 8,
    },
    "sub_gate_a_predicate": (
        "02-revisions-initial.json has exactly 1 revision (the Bicep-deployed "
        "baseline `ca-revhist-t3t3np--wdmdnoq`). The fallback path enforces "
        "the SAME exactly-1 predicate (intent-preserving per Oracle PR #279 "
        "P0-4 directive — the dual-path shape exists for JSON schema parity; "
        "weakening to `>= 1` would allow a non-fresh baseline to pass and "
        "would silently invalidate sub-gates b/c whose +10 burst-suffix "
        "interpretation assumes a 1-revision starting point)."
    ),
    "sub_gate_b_predicate": (
        "03-revisions-t0.json has exactly 11 revisions (strong, ideal burst); "
        "fallback requires at least 8 per Oracle directive."
    ),
    "sub_gate_c_predicate": (
        "03-revisions-t0.json contains 11 DISTINCT revision names (strong); "
        "fallback requires at least 8 distinct names. Proves each env-var-only "
        "update materialized a new revision rather than reusing an existing one."
    ),
    "sub_gate_a_initial_baseline_one_revision": {
        "observed_initial_revision_count": initial_count,
        "observed_first_5": sample(revs_initial),
        "a_strong_path_initial_exactly_one": a_strong_path_initial_exactly_one,
        "a_fallback_path_initial_exactly_one": a_fallback_path_initial_exactly_one,
        "a_pass": a_pass,
    },
    "sub_gate_b_post_burst_eleven_revisions": {
        "observed_post_burst_revision_count": t0_count,
        "observed_first_5": sample(revs_t0),
        "b_strong_path_t0_exactly_eleven": b_strong_path_t0_exactly_eleven,
        "b_fallback_path_t0_at_least_eight": b_fallback_path_t0_at_least_eight,
        "b_pass": b_pass,
    },
    "sub_gate_c_post_burst_distinct_revision_names": {
        "observed_distinct_revision_name_count": distinct_count,
        "observed_first_5": distinct_t0_names[:5],
        "c_strong_path_distinct_exactly_eleven": c_strong_path_distinct_exactly_eleven,
        "c_fallback_path_distinct_at_least_eight": c_fallback_path_distinct_at_least_eight,
        "c_pass": c_pass,
    },
}
result["revision_history_limit_h_burst_materialization_sub_gates"] = {
    "a_initial_baseline_one_revision": result["sub_gate_a_initial_baseline_one_revision"]["a_pass"],
    "b_post_burst_eleven_revisions": result["sub_gate_b_post_burst_eleven_revisions"]["b_pass"],
    "c_post_burst_distinct_revision_names": result["sub_gate_c_post_burst_distinct_revision_names"]["c_pass"],
}
result["revision_history_limit_h_burst_materialization_all_subgates_pass"] = all(
    result["revision_history_limit_h_burst_materialization_sub_gates"].values()
)
result["gate_classification"] = "env_var_only_updates_materialized_distinct_new_revisions"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 23: bounded-window non-pruning gate ==="
UTC_NOW="$UTC_NOW" \
REVS_T5M_FILE="$REVS_T5M_FILE" \
REVS_T15M_FILE="$REVS_T15M_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE23_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


def sample(items, n=5):
    return items[:n]


def count_inactive(records):
    return sum(1 for record in records if not bool(record.get("active", False)))


revs_t5m_path = pathlib.Path(os.environ["REVS_T5M_FILE"])
revs_t15m_path = pathlib.Path(os.environ["REVS_T15M_FILE"])

revs_t5m = json.loads(revs_t5m_path.read_text())
revs_t15m = json.loads(revs_t15m_path.read_text())

t5m_inactive = count_inactive(revs_t5m)
t15m_inactive = count_inactive(revs_t15m)
t5m_total = len(revs_t5m)
t15m_total = len(revs_t15m)

CONFIGURED_LIMIT = 2
STRONG_INACTIVE_FLOOR = 8

# Sub-gate (a): t+5m inactive count > 2 (strong: >= 8) or > 2 (fallback).
# The configured target is 2 inactive revisions. The strong path
# requires the inactive count to be substantially above target (>= 8),
# which matches the canonical 2026-06-22 reproduction.
a_strong_path_t5m_inactive_ge_eight = t5m_inactive >= STRONG_INACTIVE_FLOOR
a_fallback_path_t5m_inactive_gt_two = t5m_inactive > CONFIGURED_LIMIT
a_pass = a_strong_path_t5m_inactive_ge_eight or a_fallback_path_t5m_inactive_gt_two

# Sub-gate (b): t+15m inactive count > 2 (strong: >= 8) or > 2 (fallback).
b_strong_path_t15m_inactive_ge_eight = t15m_inactive >= STRONG_INACTIVE_FLOOR
b_fallback_path_t15m_inactive_gt_two = t15m_inactive > CONFIGURED_LIMIT
b_pass = b_strong_path_t15m_inactive_ge_eight or b_fallback_path_t15m_inactive_gt_two

# Sub-gate (c): BOTH-not-OR per Lab 19 P0 lesson. The bounded-observation
# claim depends on BOTH endpoints of the window, not either-or. ALSO
# requires monotonic non-decrease (t15m >= t5m) to prove pruning did not
# start partway through the window.
both_endpoints_above_target = (
    t5m_inactive > CONFIGURED_LIMIT and t15m_inactive > CONFIGURED_LIMIT
)
monotonic_non_decrease = t15m_inactive >= t5m_inactive
c_strong_path_both_above_floor_and_monotonic = (
    t5m_inactive >= STRONG_INACTIVE_FLOOR
    and t15m_inactive >= STRONG_INACTIVE_FLOOR
    and monotonic_non_decrease
)
c_fallback_path_both_above_target_and_monotonic = (
    both_endpoints_above_target and monotonic_non_decrease
)
c_pass = c_strong_path_both_above_floor_and_monotonic or c_fallback_path_both_above_target_and_monotonic

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "revision_history_limit_bounded_observation",
    "hypothesis": "H2_bounded_window_non_pruning",
    "claim": "pruning_was_not_prompt_within_this_15_minute_observation_window_in_this_reproduction",
    "claim_level": "Observed",
    "claim_ceiling_warning": (
        "This gate proves only that pruning was not prompt within the 15-minute "
        "window in this single reproduction. It does NOT prove the platform "
        "never prunes promptly, nor does it characterize the long-run pruning "
        "cadence. The pruning interval is undocumented and there is no SLA."
    ),
    "predicate_inputs": {
        "revs_t5m_path": repo_rel(revs_t5m_path),
        "revs_t15m_path": repo_rel(revs_t15m_path),
    },
    "thresholds": {
        "configured_max_inactive_revisions": CONFIGURED_LIMIT,
        "strong_inactive_floor": STRONG_INACTIVE_FLOOR,
    },
    "sub_gate_a_predicate": (
        "At t+5m, inactive revision count > 2 (configured limit). "
        "Strong path requires >= 8; fallback requires only > 2."
    ),
    "sub_gate_b_predicate": (
        "At t+15m, inactive revision count > 2 (configured limit). "
        "Strong path requires >= 8; fallback requires only > 2."
    ),
    "sub_gate_c_predicate": (
        "BOTH-not-OR per Lab 19 P0 lesson: BOTH t+5m AND t+15m show inactive > 2, "
        "AND t+15m inactive count >= t+5m inactive count (monotonic non-decrease). "
        "Strong path requires both endpoints >= 8 floor and monotonic; "
        "fallback requires both endpoints > 2 target and monotonic."
    ),
    "sub_gate_a_t5m_inactive_above_target": {
        "observed_t5m_total_revisions": t5m_total,
        "observed_t5m_inactive_count": t5m_inactive,
        "observed_first_5": sample(revs_t5m),
        "a_strong_path_t5m_inactive_ge_eight": a_strong_path_t5m_inactive_ge_eight,
        "a_fallback_path_t5m_inactive_gt_two": a_fallback_path_t5m_inactive_gt_two,
        "a_pass": a_pass,
    },
    "sub_gate_b_t15m_inactive_above_target": {
        "observed_t15m_total_revisions": t15m_total,
        "observed_t15m_inactive_count": t15m_inactive,
        "observed_first_5": sample(revs_t15m),
        "b_strong_path_t15m_inactive_ge_eight": b_strong_path_t15m_inactive_ge_eight,
        "b_fallback_path_t15m_inactive_gt_two": b_fallback_path_t15m_inactive_gt_two,
        "b_pass": b_pass,
    },
    "sub_gate_c_both_endpoints_above_target_and_monotonic": {
        "observed_t5m_inactive_count": t5m_inactive,
        "observed_t15m_inactive_count": t15m_inactive,
        "observed_both_endpoints_above_target": both_endpoints_above_target,
        "observed_monotonic_non_decrease": monotonic_non_decrease,
        "c_strong_path_both_above_floor_and_monotonic": c_strong_path_both_above_floor_and_monotonic,
        "c_fallback_path_both_above_target_and_monotonic": c_fallback_path_both_above_target_and_monotonic,
        "c_pass": c_pass,
    },
}
result["revision_history_limit_h2_bounded_window_non_pruning_sub_gates"] = {
    "a_t5m_inactive_above_target": result["sub_gate_a_t5m_inactive_above_target"]["a_pass"],
    "b_t15m_inactive_above_target": result["sub_gate_b_t15m_inactive_above_target"]["b_pass"],
    "c_both_endpoints_above_target_and_monotonic": result["sub_gate_c_both_endpoints_above_target_and_monotonic"]["c_pass"],
}
result["revision_history_limit_h2_bounded_window_non_pruning_all_subgates_pass"] = all(
    result["revision_history_limit_h2_bounded_window_non_pruning_sub_gates"].values()
)
result["gate_classification"] = "pruning_was_not_prompt_within_this_15_minute_observation_window_in_this_reproduction"
print(json.dumps(result, indent=2))
PY

echo "=== Phase summary ==="
GATE20_FILE="$GATE20_FILE" \
GATE21_FILE="$GATE21_FILE" \
GATE22_FILE="$GATE22_FILE" \
GATE23_FILE="$GATE23_FILE" \
python3 <<'PY'
import json
import os
import pathlib
import sys

gates = [
    (
        "20",
        "cohort_integrity",
        pathlib.Path(os.environ["GATE20_FILE"]),
        "revision_history_limit_h_cohort_integrity_sub_gates",
        "revision_history_limit_h_cohort_integrity_all_subgates_pass",
    ),
    (
        "21",
        "config_persistence",
        pathlib.Path(os.environ["GATE21_FILE"]),
        "revision_history_limit_h1_config_persistence_sub_gates",
        "revision_history_limit_h1_config_persistence_all_subgates_pass",
    ),
    (
        "22",
        "burst_materialization",
        pathlib.Path(os.environ["GATE22_FILE"]),
        "revision_history_limit_h_burst_materialization_sub_gates",
        "revision_history_limit_h_burst_materialization_all_subgates_pass",
    ),
    (
        "23",
        "bounded_window_non_pruning",
        pathlib.Path(os.environ["GATE23_FILE"]),
        "revision_history_limit_h2_bounded_window_non_pruning_sub_gates",
        "revision_history_limit_h2_bounded_window_non_pruning_all_subgates_pass",
    ),
]

overall = True
print("gate | name                           | sub-gates                                                 | overall")
print("-----|--------------------------------|-----------------------------------------------------------|--------")
for gate_id, name, path, sub_key, overall_key in gates:
    data = json.loads(path.read_text())
    subs = data[sub_key]
    sub_summary = ", ".join(f"{k}={'PASS' if v else 'FAIL'}" for k, v in subs.items())
    gate_pass = bool(data[overall_key])
    overall = overall and gate_pass
    print(f"{gate_id:>4} | {name:<30} | {sub_summary:<57} | {'PASS' if gate_pass else 'FAIL'}")

print("")
print(f"overall_phase_b_verdict={'PASS' if overall else 'FAIL'}")
sys.exit(0 if overall else 1)
PY
