#!/usr/bin/env bash
# verify.sh — Phase B evidence-pack verification for Lab 21
# (acr-pull-failure).
#
# File purpose
# ------------
# Phase B verify.sh — pure file processor — emits 4 falsifiable gate JSONs
# from committed canonical evidence. This script reads ONLY the canonical
# 00-/01-/.../23- evidence files already checked into
# `labs/acr-pull-failure/evidence/` and writes the derived gate outputs:
#
#   - 30-cohort-integrity-gate.json
#   - 31-failure-attribution-gate.json
#   - 32-recovery-materialization-gate.json
#   - 33-in-place-recovery-continuity-gate.json
#
# It MUST NOT call Azure, curl remote endpoints, or depend on any live cloud
# state. A reviewer must be able to re-run this script after the lab RG has
# been deleted and still obtain the same verdict from the same committed
# evidence.
#
# Oracle ses_105f57cf7ffeKwLIxEdGFI0JmQ directives (verbatim, binding)
# -------------------------------------------------------------------
#   Q1: Keep four gates, drop Gate 31 ingress.fqdn check, drop Gate 31
#       sub-d (LA non-materialization claim), drop Gate 33 timestamp /
#       no-recreation proof, drop Gate 33 same-ACR proof unless registry
#       identity is explicit in the JSON.
#   Q2: Option B (Single canonical). 01-deployment-operations-failed.json
#       is the MANIFEST_UNKNOWN canonical source. 01-deployment-result.json
#       is optional corroboration. NO dual-path scaffolding for the
#       smoking-gun predicate.
#   Q3: Option A. PII fix in the same Phase B PR.
#   Q4: Yes. Restate the 06-h1-gate.json timestamp backfill caveat in
#       evidence/README.md and cross-reference the lab README's
#       "Honest disclosure" note.
#   Q5: Option C. The post-fix KQL silent_acceptable_post_fix
#       classification is INFORMATIONAL only, NOT promoted to a gate.
#
#   "Only use dual-path scaffolding where there are two genuinely
#    equivalent manifestations of the same claim."
#   "Bound every absence predicate to the failed-deployment cohort."
#   Target verify.sh size: 820-900 lines (~850).
#
# Numbered prefix policy
# ----------------------
# 00-/01-/.../23- = canonical committed evidence inputs (Phase A outputs).
#   This lab uses 00-14 for the H1+H2 capture sequence and 20-23 for the
#   post-run metadata (CLI versions, extension version, region, deployment
#   outputs). The 06-h1-gate.json and 14-h2-gate.json files are written by
#   Phase A scripts (trigger.sh and fix-and-capture.sh respectively) but
#   are part of the canonical cohort consumed by Phase B.
# 30-/31-/32-/33- = derived Phase B gate outputs generated by this script.
#
# The 30-33 prefix is intentional — it avoids collision with the canonical
# 20-23 files that Phase A already wrote (cli-versions, cli-containerapp-ext,
# region, deployment-outputs). If this script used 20-23 (as Lab 20 does),
# the Gate 20 JSON would overwrite the canonical 20-cli-versions.json
# artifact and orphan the evidence. Each lab's Phase B output prefix is
# chosen to skip past the highest canonical Phase A prefix in its cohort.
#
# What the four gates prove
# -------------------------
# Gate 30 = cohort integrity gate.
#   Claim: the canonical evidence pack is internally coherent before any
#   hypothesis reasoning starts. This gate consumes the 24 canonical files
#   but reasons about presence, temporal coherence of script start
#   timestamps, no-extras, and README cross-reference only.
#
# Gate 31 = failure attribution gate.
#   Claim: the failed deployment carries the MANIFEST_UNKNOWN smoking gun
#   AND the Container App resource exhibits the absence cohort
#   (provisioningState=Failed, latestRevisionName=null, revision list
#   empty, ACR repository absent) consistent with manifest resolution
#   never reaching revision creation. This is the H1 falsification check.
#   All five sub-gates use single-path predicates per Oracle Q2 directive.
#
# Gate 32 = recovery materialization gate.
#   Claim: after the operator builds and pushes labacr:v1 via az acr build
#   and updates the Container App to reference it, the platform creates a
#   Healthy revision serving 100% of traffic, the assigned FQDN returns
#   HTTP 200, and the ACR repository + tag exist. Sub-gate (c) is the only
#   dual-path predicate (curl 10/10 strong vs >=8/10 fallback) — Oracle Q1
#   directive: dual-path only where equivalent manifestations exist.
#
# Gate 33 = in-place recovery continuity gate.
#   Claim: the recovery is an IN-PLACE fix — the same Container App
#   resource identity transitions from the failed-baseline state cohort
#   to the recovered state cohort by changing only the image tag (from
#   ":does-not-exist" to ":v1") while keeping the same ACR login server.
#   This rules out the recovery being achieved by recreating a different
#   Container App resource or pointing at a different registry. Single-path
#   predicates only per Oracle Q1 directive (dropped: timestamp proof,
#   no-recreation proof, same-ACR proof relying on identity beyond what
#   the JSON encodes).
#
# Verdict semantics encoded by this script
# ---------------------------------------
# Gate 30 PASS = the evidence cohort is internally consistent.
# Gate 31 PASS = the failed-deployment cohort is fully attributable to a
#   manifest resolution failure with MANIFEST_UNKNOWN (H1 not falsified).
# Gate 32 PASS = the az acr build + az containerapp update flow materialized
#   a Healthy serving revision (H2 not falsified).
# Gate 33 PASS = the recovery is in-place (same app, same registry, only
#   the image tag changed).
#
# Gate 31 + Gate 32 together encode the lab's main claim: the existence
# of the referenced image tag in ACR is the single controlling variable
# for this failure mode. Gate 33 strengthens this by proving the recovery
# does not depend on changing any other resource identity.
#
# Claim ceiling (strict, Oracle directive)
# ----------------------------------------
# The supported claim from this evidence is:
#   "In this 2026-06-22 koreacentral reproduction, referencing a
#    non-existent ACR image tag causes a deployment-level failure with
#    MANIFEST_UNKNOWN, and rebuilding + updating to a valid tag recovers
#    the same Container App resource in-place."
# NOT:
#   "The platform always emits MANIFEST_UNKNOWN for missing tags."
#   "Recovery always completes within N minutes."
#   "ContainerAppSystemLogs_CL is never materialized in this failure mode."
# The honest-disclosure caveats in lab README + evidence/README.md
# document the empirical scope of this reproduction.
#
# QUOTED heredoc rule (mandatory)
# -------------------------------
# ALL Python heredocs in this file MUST use `<<'PY'` (single-quoted
# delimiter) to prevent shell expansion of `$` characters inside Python
# code. This is a Lab 14 lesson 29 mandatory rule. Unquoted `<<PY` would
# cause `$variable` in Python to be silently replaced by bash before the
# heredoc reaches python3.
#
# REPO_RELATIVE_EVIDENCE_DIR rule (mandatory)
# -------------------------------------------
# All gate JSONs MUST cite predicate inputs as repo-relative paths (for
# example `labs/acr-pull-failure/evidence/01-deployment-operations-failed.json`),
# NOT absolute paths. This prevents `/Users/<alias>/...` leakage into
# committed evidence and keeps the pack reproducible across operator
# machines.
#
# Record-scoped predicate rule (mandatory)
# ----------------------------------------
# Lab 15 lesson 34 — no whole-file substring searches except where the
# predicate input is a single embedded human-readable string (the
# MANIFEST_UNKNOWN smoking-gun message inside
# 01-deployment-operations-failed.json's statusMessage.error.message,
# which is itself the parsed record). Every other assertion comes from
# parsed JSON records. This script uses Python `json.load()` plus record
# iteration. It never greps the canonical JSON files to count matches.
#
# BOTH-not-OR rule (Lab 19 P0 lesson)
# ----------------------------------
# Where a hypothesis claim is about multiple required conditions, the
# gate predicate uses AND (not OR) between the conditions. Gate 31
# claims the failed-deployment cohort is *fully* attributable to manifest
# failure — every absence predicate (a-e) must hold simultaneously, not
# just one of them. Gate 33 similarly requires the identity match
# (sub-gate a) AND the state transition (sub-gate b) AND the image-tag
# delta with same registry (sub-gate c).
#
# Failed-deployment cohort binding rule (Oracle directive)
# --------------------------------------------------------
# "Bound every absence predicate to the failed-deployment cohort."
# Gate 31's absence predicates (revision list empty, ACR repository
# absent) are interpretable as evidence ONLY when read together with
# the deployment failure signal. A revision list could be empty for many
# unrelated reasons (the app was just deleted, the user typo'd the app
# name, etc.). What makes this absence diagnostic is that it co-occurs
# with a Failed deployment that carries MANIFEST_UNKNOWN. The gate JSONs
# express this by recording the deployment failure attribution in the
# same predicate_inputs block as the absence predicates, so a reader
# cannot interpret the absences without the failure context.
#
# Canonical evidence consumed by this script
# ------------------------------------------
# Gate 30 consumes:
#   ALL 24 canonical files (presence + temporal + extras + README)
#
# Gate 31 consumes:
#   01-deployment-result.json                    (provisioningState=Failed corroboration)
#   01-deployment-operations-failed.json         (MANIFEST_UNKNOWN canonical source per Oracle Q2)
#   02-containerapp-show-baseline.json           (app provisioningState=Failed, latestRevisionName=null)
#   03-revisions-list-baseline.json              (empty array)
#   04-acr-repository-list-baseline.json         (does not contain "labacr")
#
# Gate 32 consumes:
#   08-containerapp-update-result.json           (post-update provisioningState=Succeeded, latestRevisionName populated)
#   10-revisions-list-after-fix.json             (Healthy + trafficWeight=100)
#   11-acr-repository-list-after-fix.json        (contains "labacr")
#   11-acr-repository-show-tags-after-fix.json   (contains "v1")
#   12-curl-after-fix.json                       (requests_ok)
#
# Gate 33 consumes:
#   02-containerapp-show-baseline.json           (baseline image, name)
#   09-containerapp-show-after-fix.json          (after-fix image, name)
#   10-revisions-list-after-fix.json             (after-fix Healthy revision count)
#
# Files explicitly NOT consumed by this script (Phase B gate inputs)
# ------------------------------------------------------------------
# These canonical files are part of the cohort (Gate 30 checks their
# presence) but are NOT used as predicate inputs by Gates 31-33:
#   - 00-trigger-run.txt          (Phase A trigger.sh stdout, human-readable; Gate 30 timestamp extraction only)
#   - 00-verify-run.txt           (Phase A fix-and-capture.sh stdout; Gate 30 timestamp extraction only)
#   - 05-system-logs-show-error.txt (Phase A system-log absence evidence; descriptive only)
#   - 06-activity-log-failed.json (Phase A activity-log corroboration; descriptive only)
#   - 06-h1-gate.json             (Phase A H1 gate parsed by trigger.sh; Gate 30 cohort presence only)
#   - 07-acr-build-result.json    (Phase A ACR build log; descriptive only)
#   - 13-kql-after-fix.json       (Phase A post-fix KQL classification; INFORMATIONAL per Oracle Q5)
#   - 13-kql-after-fix-raw.txt    (Phase A raw KQL stdout; INFORMATIONAL per Oracle Q5)
#   - 14-h2-gate.json             (Phase A H2 gate parsed by fix-and-capture.sh; Gate 30 cohort presence only)
#   - 20-cli-versions.json        (operator environment metadata)
#   - 21-cli-containerapp-ext.json (operator environment metadata)
#   - 22-region.json              (region metadata)
#   - 23-deployment-outputs.json  (Bicep deployment outputs)
#
# Usage
# -----
#   bash labs/acr-pull-failure/verify.sh
#
# No environment variables are required.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_DIR="$SCRIPT_DIR"
EVIDENCE_DIR="$LAB_DIR/evidence"
REPO_RELATIVE_EVIDENCE_DIR="labs/acr-pull-failure/evidence"
UTC_NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Canonical input files (Phase A outputs, 24 files).
TRIGGER_LOG_FILE="$EVIDENCE_DIR/00-trigger-run.txt"
CAPTURE_LOG_FILE="$EVIDENCE_DIR/00-verify-run.txt"
DEPLOYMENT_RESULT_FILE="$EVIDENCE_DIR/01-deployment-result.json"
DEPLOYMENT_OPS_FILE="$EVIDENCE_DIR/01-deployment-operations-failed.json"
CONTAINERAPP_BASELINE_FILE="$EVIDENCE_DIR/02-containerapp-show-baseline.json"
REVS_BASELINE_FILE="$EVIDENCE_DIR/03-revisions-list-baseline.json"
ACR_REPO_LIST_BASELINE_FILE="$EVIDENCE_DIR/04-acr-repository-list-baseline.json"
SYSTEM_LOGS_ERROR_FILE="$EVIDENCE_DIR/05-system-logs-show-error.txt"
ACTIVITY_LOG_FILE="$EVIDENCE_DIR/06-activity-log-failed.json"
H1_GATE_FILE="$EVIDENCE_DIR/06-h1-gate.json"
ACR_BUILD_FILE="$EVIDENCE_DIR/07-acr-build-result.json"
CONTAINERAPP_UPDATE_FILE="$EVIDENCE_DIR/08-containerapp-update-result.json"
CONTAINERAPP_AFTER_FIX_FILE="$EVIDENCE_DIR/09-containerapp-show-after-fix.json"
REVS_AFTER_FIX_FILE="$EVIDENCE_DIR/10-revisions-list-after-fix.json"
ACR_REPO_LIST_AFTER_FIX_FILE="$EVIDENCE_DIR/11-acr-repository-list-after-fix.json"
ACR_REPO_TAGS_AFTER_FIX_FILE="$EVIDENCE_DIR/11-acr-repository-show-tags-after-fix.json"
CURL_AFTER_FIX_FILE="$EVIDENCE_DIR/12-curl-after-fix.json"
KQL_AFTER_FIX_FILE="$EVIDENCE_DIR/13-kql-after-fix.json"
KQL_AFTER_FIX_RAW_FILE="$EVIDENCE_DIR/13-kql-after-fix-raw.txt"
H2_GATE_FILE="$EVIDENCE_DIR/14-h2-gate.json"
CLI_VERSIONS_FILE="$EVIDENCE_DIR/20-cli-versions.json"
CLI_EXT_FILE="$EVIDENCE_DIR/21-cli-containerapp-ext.json"
REGION_FILE="$EVIDENCE_DIR/22-region.json"
DEPLOYMENT_OUTPUTS_FILE="$EVIDENCE_DIR/23-deployment-outputs.json"

# Phase B gate output files (30-33 prefix avoids collision with 20-23
# canonical Phase A metadata files).
GATE30_FILE="$EVIDENCE_DIR/30-cohort-integrity-gate.json"
GATE31_FILE="$EVIDENCE_DIR/31-failure-attribution-gate.json"
GATE32_FILE="$EVIDENCE_DIR/32-recovery-materialization-gate.json"
GATE33_FILE="$EVIDENCE_DIR/33-in-place-recovery-continuity-gate.json"

for required in \
    "$TRIGGER_LOG_FILE" \
    "$CAPTURE_LOG_FILE" \
    "$DEPLOYMENT_RESULT_FILE" \
    "$DEPLOYMENT_OPS_FILE" \
    "$CONTAINERAPP_BASELINE_FILE" \
    "$REVS_BASELINE_FILE" \
    "$ACR_REPO_LIST_BASELINE_FILE" \
    "$SYSTEM_LOGS_ERROR_FILE" \
    "$ACTIVITY_LOG_FILE" \
    "$H1_GATE_FILE" \
    "$ACR_BUILD_FILE" \
    "$CONTAINERAPP_UPDATE_FILE" \
    "$CONTAINERAPP_AFTER_FIX_FILE" \
    "$REVS_AFTER_FIX_FILE" \
    "$ACR_REPO_LIST_AFTER_FIX_FILE" \
    "$ACR_REPO_TAGS_AFTER_FIX_FILE" \
    "$CURL_AFTER_FIX_FILE" \
    "$KQL_AFTER_FIX_FILE" \
    "$KQL_AFTER_FIX_RAW_FILE" \
    "$H2_GATE_FILE" \
    "$CLI_VERSIONS_FILE" \
    "$CLI_EXT_FILE" \
    "$REGION_FILE" \
    "$DEPLOYMENT_OUTPUTS_FILE"; do
    if [[ ! -f "$required" ]]; then
        echo "ERROR: required canonical evidence file missing: $required" >&2
        echo "This Phase B verify.sh is a pure file processor and cannot synthesize missing evidence." >&2
        exit 1
    fi
done

echo "=== Phase 30: cohort integrity gate ==="
UTC_NOW="$UTC_NOW" \
EVIDENCE_DIR="$EVIDENCE_DIR" \
TRIGGER_LOG_FILE="$TRIGGER_LOG_FILE" \
CAPTURE_LOG_FILE="$CAPTURE_LOG_FILE" \
DEPLOYMENT_RESULT_FILE="$DEPLOYMENT_RESULT_FILE" \
DEPLOYMENT_OPS_FILE="$DEPLOYMENT_OPS_FILE" \
CONTAINERAPP_BASELINE_FILE="$CONTAINERAPP_BASELINE_FILE" \
REVS_BASELINE_FILE="$REVS_BASELINE_FILE" \
ACR_REPO_LIST_BASELINE_FILE="$ACR_REPO_LIST_BASELINE_FILE" \
SYSTEM_LOGS_ERROR_FILE="$SYSTEM_LOGS_ERROR_FILE" \
ACTIVITY_LOG_FILE="$ACTIVITY_LOG_FILE" \
H1_GATE_FILE="$H1_GATE_FILE" \
ACR_BUILD_FILE="$ACR_BUILD_FILE" \
CONTAINERAPP_UPDATE_FILE="$CONTAINERAPP_UPDATE_FILE" \
CONTAINERAPP_AFTER_FIX_FILE="$CONTAINERAPP_AFTER_FIX_FILE" \
REVS_AFTER_FIX_FILE="$REVS_AFTER_FIX_FILE" \
ACR_REPO_LIST_AFTER_FIX_FILE="$ACR_REPO_LIST_AFTER_FIX_FILE" \
ACR_REPO_TAGS_AFTER_FIX_FILE="$ACR_REPO_TAGS_AFTER_FIX_FILE" \
CURL_AFTER_FIX_FILE="$CURL_AFTER_FIX_FILE" \
KQL_AFTER_FIX_FILE="$KQL_AFTER_FIX_FILE" \
KQL_AFTER_FIX_RAW_FILE="$KQL_AFTER_FIX_RAW_FILE" \
H2_GATE_FILE="$H2_GATE_FILE" \
CLI_VERSIONS_FILE="$CLI_VERSIONS_FILE" \
CLI_EXT_FILE="$CLI_EXT_FILE" \
REGION_FILE="$REGION_FILE" \
DEPLOYMENT_OUTPUTS_FILE="$DEPLOYMENT_OUTPUTS_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE30_FILE"
import json
import os
import pathlib
import re
from datetime import datetime, timezone


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


def sample(items, n=5):
    return items[:n]


canonical_paths = [
    pathlib.Path(os.environ["TRIGGER_LOG_FILE"]),
    pathlib.Path(os.environ["CAPTURE_LOG_FILE"]),
    pathlib.Path(os.environ["DEPLOYMENT_RESULT_FILE"]),
    pathlib.Path(os.environ["DEPLOYMENT_OPS_FILE"]),
    pathlib.Path(os.environ["CONTAINERAPP_BASELINE_FILE"]),
    pathlib.Path(os.environ["REVS_BASELINE_FILE"]),
    pathlib.Path(os.environ["ACR_REPO_LIST_BASELINE_FILE"]),
    pathlib.Path(os.environ["SYSTEM_LOGS_ERROR_FILE"]),
    pathlib.Path(os.environ["ACTIVITY_LOG_FILE"]),
    pathlib.Path(os.environ["H1_GATE_FILE"]),
    pathlib.Path(os.environ["ACR_BUILD_FILE"]),
    pathlib.Path(os.environ["CONTAINERAPP_UPDATE_FILE"]),
    pathlib.Path(os.environ["CONTAINERAPP_AFTER_FIX_FILE"]),
    pathlib.Path(os.environ["REVS_AFTER_FIX_FILE"]),
    pathlib.Path(os.environ["ACR_REPO_LIST_AFTER_FIX_FILE"]),
    pathlib.Path(os.environ["ACR_REPO_TAGS_AFTER_FIX_FILE"]),
    pathlib.Path(os.environ["CURL_AFTER_FIX_FILE"]),
    pathlib.Path(os.environ["KQL_AFTER_FIX_FILE"]),
    pathlib.Path(os.environ["KQL_AFTER_FIX_RAW_FILE"]),
    pathlib.Path(os.environ["H2_GATE_FILE"]),
    pathlib.Path(os.environ["CLI_VERSIONS_FILE"]),
    pathlib.Path(os.environ["CLI_EXT_FILE"]),
    pathlib.Path(os.environ["REGION_FILE"]),
    pathlib.Path(os.environ["DEPLOYMENT_OUTPUTS_FILE"]),
]
evidence_dir = pathlib.Path(os.environ["EVIDENCE_DIR"])
trigger_log_path = pathlib.Path(os.environ["TRIGGER_LOG_FILE"])
capture_log_path = pathlib.Path(os.environ["CAPTURE_LOG_FILE"])
deployment_result_path = pathlib.Path(os.environ["DEPLOYMENT_RESULT_FILE"])

# Sub-gate (a): all 24 canonical files exist.
presence_records = [{"path": repo_rel(p), "exists": p.exists()} for p in canonical_paths]
present_count = sum(1 for item in presence_records if item["exists"])
a_strong_path_all_24_files_exist = present_count == 24
a_fallback_path_at_least_22_files_exist = present_count >= 22
a_pass = a_strong_path_all_24_files_exist or a_fallback_path_at_least_22_files_exist

# Sub-gate (b): temporal coherence. The deployment timestamp (from
# 01-deployment-result.json.timestamp), the trigger.sh start line (from
# 00-trigger-run.txt:1), and the fix-and-capture.sh start line (from
# 00-verify-run.txt:1) must be monotonic and all fall within a 30-minute
# window (strong) / 60-minute window (fallback). This proves the cohort
# was captured as one coherent sequence, not stitched from disparate runs.
# Bash-quoting backfill caveat: 06-h1-gate.json.utc_captured may have been
# backfilled (see lab README "06-h1-gate.json timestamp backfill" note).
# This sub-gate does NOT use that timestamp — it uses script-start lines
# that the run captured at runtime via tee.
ISO_RE = re.compile(r"(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:[.\d]+)?(?:Z|[+-]\d{2}:\d{2})?")
b_temporal_records = {}
b_strong_path_monotonic_within_30min = False
b_fallback_path_monotonic_within_60min = False
try:
    deployment_data = json.loads(deployment_result_path.read_text())
    deployment_ts_raw = deployment_data.get("timestamp")
    # Parse "2026-06-22T13:20:46.091681+00:00" into UTC.
    if deployment_ts_raw:
        deployment_dt = datetime.fromisoformat(deployment_ts_raw.replace("Z", "+00:00"))
        if deployment_dt.tzinfo is None:
            deployment_dt = deployment_dt.replace(tzinfo=timezone.utc)
    else:
        deployment_dt = None

    trigger_first_line = trigger_log_path.read_text().splitlines()[0] if trigger_log_path.read_text().strip() else ""
    capture_first_line = capture_log_path.read_text().splitlines()[0] if capture_log_path.read_text().strip() else ""

    trigger_match = ISO_RE.search(trigger_first_line)
    capture_match = ISO_RE.search(capture_first_line)
    trigger_dt = (
        datetime.fromisoformat(trigger_match.group(1) + "+00:00")
        if trigger_match
        else None
    )
    capture_dt = (
        datetime.fromisoformat(capture_match.group(1) + "+00:00")
        if capture_match
        else None
    )

    b_temporal_records = {
        "deployment_timestamp_iso": deployment_ts_raw,
        "trigger_first_line": trigger_first_line,
        "capture_first_line": capture_first_line,
        "trigger_start_iso": trigger_dt.isoformat() if trigger_dt else None,
        "capture_start_iso": capture_dt.isoformat() if capture_dt else None,
    }
    if deployment_dt and trigger_dt and capture_dt:
        monotonic = deployment_dt <= trigger_dt <= capture_dt
        span_seconds = (capture_dt - deployment_dt).total_seconds()
        b_temporal_records["monotonic_deployment_trigger_capture"] = monotonic
        b_temporal_records["span_seconds_deployment_to_capture"] = span_seconds
        b_strong_path_monotonic_within_30min = monotonic and span_seconds <= 30 * 60
        b_fallback_path_monotonic_within_60min = monotonic and span_seconds <= 60 * 60
    else:
        b_temporal_records["parse_error"] = "missing_one_of_three_timestamps"
except (ValueError, KeyError, OSError, IndexError) as exc:
    b_temporal_records = {
        "parse_error": str(exc),
        "deployment_result_path": repo_rel(deployment_result_path),
        "trigger_log_path": repo_rel(trigger_log_path),
        "capture_log_path": repo_rel(capture_log_path),
    }
b_pass = b_strong_path_monotonic_within_30min or b_fallback_path_monotonic_within_60min

# Sub-gate (c): no unexpected non-junk extras. Lab 19 P0 lesson — the
# fallback path must REJECT any non-junk extras, not just check for junk
# patterns. Phase B outputs (30-33 gate JSONs) and README.md are expected
# and excluded; everything else outside the canonical 24 is an unexpected
# extra unless it matches the allowed-junk pattern.
canonical_names = {p.name for p in canonical_paths}
phase_b_outputs = {
    "30-cohort-integrity-gate.json",
    "31-failure-attribution-gate.json",
    "32-recovery-materialization-gate.json",
    "33-in-place-recovery-continuity-gate.json",
}
expected_meta = {"README.md"}
actual_names = {p.name for p in evidence_dir.iterdir() if p.is_file()}
extras_found = sorted(actual_names - canonical_names - phase_b_outputs - expected_meta)
missing_canonical = sorted(canonical_names - actual_names)

ALLOWED_JUNK_SUFFIXES = (".swp", ".bak", ".tmp")
ALLOWED_JUNK_EXACT_NAMES = (".DS_Store",)


def is_allowed_junk(name):
    return (
        name in ALLOWED_JUNK_EXACT_NAMES
        or any(name.endswith(suffix) for suffix in ALLOWED_JUNK_SUFFIXES)
    )


unexpected_non_junk_extras = [f for f in extras_found if not is_allowed_junk(f)]
c_strong_path_exact_match = len(extras_found) == 0 and len(missing_canonical) == 0
c_fallback_path_no_foreign_files = (
    len(missing_canonical) == 0 and len(unexpected_non_junk_extras) == 0
)
c_pass = c_strong_path_exact_match or c_fallback_path_no_foreign_files

# Sub-gate (d): README.md cross-references all 4 Phase B gate JSON
# filenames. Strong path requires the README to mention every gate JSON
# by exact name; fallback path requires the README file to exist (so a
# future maintainer at least has a starting point for the provenance
# trail).
readme_path = evidence_dir / "README.md"
d_readme_exists = readme_path.exists()
d_strong_path_readme_references_all_gates = False
d_fallback_path_readme_exists = d_readme_exists
gate_reference_records = []
if d_readme_exists:
    readme_text = readme_path.read_text()
    gate_reference_records = [
        {"gate_filename": gate_name, "mentioned_in_readme": gate_name in readme_text}
        for gate_name in sorted(phase_b_outputs)
    ]
    d_strong_path_readme_references_all_gates = all(
        item["mentioned_in_readme"] for item in gate_reference_records
    )
d_pass = d_strong_path_readme_references_all_gates or d_fallback_path_readme_exists

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "acr_pull_failure_manifest_unknown",
    "hypothesis": "H_cohort_integrity",
    "claim": "evidence_cohort_is_internally_consistent_and_temporally_coherent",
    "claim_level": "Observed",
    "predicate_inputs": {
        "evidence_dir": os.environ["REPO_RELATIVE_EVIDENCE_DIR"],
        "canonical_files_manifest": sorted(canonical_names),
        "phase_b_outputs_manifest": sorted(phase_b_outputs),
        "expected_meta_files": sorted(expected_meta),
    },
    "sub_gate_a_predicate": (
        "All 24 canonical Phase A files exist; fallback requires at least 22."
    ),
    "sub_gate_b_predicate": (
        "Deployment timestamp (01-deployment-result.timestamp), trigger.sh start "
        "line (00-trigger-run.txt:1), and fix-and-capture.sh start line "
        "(00-verify-run.txt:1) are monotonic and span <= 30 minutes (strong) / "
        "<= 60 minutes (fallback). Uses runtime-captured tee output, NOT the "
        "backfilled 06-h1-gate.json.utc_captured timestamp."
    ),
    "sub_gate_c_predicate": (
        "No unexpected non-junk extras under evidence/. Strong path requires exact match "
        "of the canonical 24 + 4 Phase B outputs + README.md; fallback tolerates only "
        "editor/OS junk (.swp/.bak/.tmp/.DS_Store) and STILL requires zero missing canonical files."
    ),
    "sub_gate_d_predicate": (
        "evidence/README.md cross-references all 4 Phase B gate JSON filenames; "
        "fallback requires only that README.md exists."
    ),
    "required_canonical_file_count": 24,
    "minimum_fallback_file_count": 22,
    "sub_gate_a_canonical_files_present": {
        "observed_present_file_count": present_count,
        "observed_first_5": sample(presence_records),
        "a_strong_path_all_24_files_exist": a_strong_path_all_24_files_exist,
        "a_fallback_path_at_least_22_files_exist": a_fallback_path_at_least_22_files_exist,
        "a_pass": a_pass,
    },
    "sub_gate_b_temporal_coherence": {
        "observed_temporal_records": b_temporal_records,
        "b_strong_path_monotonic_within_30min": b_strong_path_monotonic_within_30min,
        "b_fallback_path_monotonic_within_60min": b_fallback_path_monotonic_within_60min,
        "b_pass": b_pass,
    },
    "sub_gate_c_no_unexpected_extras": {
        "observed_extras_count": len(extras_found),
        "observed_extras": extras_found,
        "observed_missing_canonical": missing_canonical,
        "unexpected_non_junk_extras": unexpected_non_junk_extras,
        "allowed_junk_suffixes": list(ALLOWED_JUNK_SUFFIXES),
        "allowed_junk_exact_names": list(ALLOWED_JUNK_EXACT_NAMES),
        "c_strong_path_exact_match": c_strong_path_exact_match,
        "c_fallback_path_no_foreign_files": c_fallback_path_no_foreign_files,
        "c_pass": c_pass,
    },
    "sub_gate_d_readme_references_gate_outputs": {
        "observed_readme_exists": d_readme_exists,
        "observed_gate_reference_records": gate_reference_records,
        "d_strong_path_readme_references_all_gates": d_strong_path_readme_references_all_gates,
        "d_fallback_path_readme_exists": d_fallback_path_readme_exists,
        "d_pass": d_pass,
    },
}
result["acr_pull_failure_h_cohort_integrity_sub_gates"] = {
    "a_canonical_files_present": result["sub_gate_a_canonical_files_present"]["a_pass"],
    "b_temporal_coherence": result["sub_gate_b_temporal_coherence"]["b_pass"],
    "c_no_unexpected_extras": result["sub_gate_c_no_unexpected_extras"]["c_pass"],
    "d_readme_references_gate_outputs": result["sub_gate_d_readme_references_gate_outputs"]["d_pass"],
}
result["acr_pull_failure_h_cohort_integrity_all_subgates_pass"] = all(
    result["acr_pull_failure_h_cohort_integrity_sub_gates"].values()
)
result["gate_classification"] = "evidence_cohort_is_internally_consistent_and_temporally_coherent"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 31: failure attribution gate ==="
UTC_NOW="$UTC_NOW" \
DEPLOYMENT_RESULT_FILE="$DEPLOYMENT_RESULT_FILE" \
DEPLOYMENT_OPS_FILE="$DEPLOYMENT_OPS_FILE" \
CONTAINERAPP_BASELINE_FILE="$CONTAINERAPP_BASELINE_FILE" \
REVS_BASELINE_FILE="$REVS_BASELINE_FILE" \
ACR_REPO_LIST_BASELINE_FILE="$ACR_REPO_LIST_BASELINE_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE31_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


deployment_result_path = pathlib.Path(os.environ["DEPLOYMENT_RESULT_FILE"])
deployment_ops_path = pathlib.Path(os.environ["DEPLOYMENT_OPS_FILE"])
containerapp_baseline_path = pathlib.Path(os.environ["CONTAINERAPP_BASELINE_FILE"])
revs_baseline_path = pathlib.Path(os.environ["REVS_BASELINE_FILE"])
acr_repo_list_baseline_path = pathlib.Path(os.environ["ACR_REPO_LIST_BASELINE_FILE"])

deployment_result = json.loads(deployment_result_path.read_text())
deployment_ops = json.loads(deployment_ops_path.read_text())
containerapp_baseline = json.loads(containerapp_baseline_path.read_text())
revs_baseline = json.loads(revs_baseline_path.read_text())
acr_repo_list_baseline = json.loads(acr_repo_list_baseline_path.read_text())

SMOKING_GUN_TOKEN = "MANIFEST_UNKNOWN"
TARGET_REPO_NAME = "labacr"

# Sub-gate (a): deployment failed AND deployment ops carry MANIFEST_UNKNOWN.
# Single-path per Oracle Q2 (Option B canonical). The MANIFEST_UNKNOWN
# token is parsed from the deployment operations record
# (statusMessage.error.message), NOT from the deployment-result envelope
# (which only carries the generic ARM "At least one resource deployment
# operation failed" message). The deployment-result.provisioningState is
# also checked as corroboration but the canonical source for the smoking
# gun is the operations record.
deployment_provisioning_state = deployment_result.get("provisioningState")
# Iterate parsed operations records to extract per-operation
# statusMessage.error.message. This is record-scoped per Lab 15 lesson 34:
# we do not grep the file, we iterate the parsed JSON array.
ops_error_messages = []
for record in deployment_ops:
    status_message = record.get("statusMessage") or {}
    error = status_message.get("error") or {}
    message = error.get("message")
    if isinstance(message, str):
        ops_error_messages.append(message)
manifest_unknown_in_any_op = any(SMOKING_GUN_TOKEN in msg for msg in ops_error_messages)
a_predicate_holds = (
    deployment_provisioning_state == "Failed"
    and manifest_unknown_in_any_op
)
a_pass = a_predicate_holds

# Sub-gate (b): containerapp baseline.provisioningState == "Failed".
# Single-path. Bound to the failed-deployment cohort: this absence
# predicate is interpretable only because the deployment itself failed
# (sub-gate a).
containerapp_baseline_provisioning_state = containerapp_baseline.get("provisioningState")
b_predicate_holds = containerapp_baseline_provisioning_state == "Failed"
b_pass = b_predicate_holds

# Sub-gate (c): containerapp baseline.latestRevisionName == null.
# Single-path. Same cohort binding.
containerapp_baseline_latest_revision_name = containerapp_baseline.get("latestRevisionName")
c_predicate_holds = containerapp_baseline_latest_revision_name is None
c_pass = c_predicate_holds

# Sub-gate (d): revision list is empty array.
# Single-path. Same cohort binding.
d_predicate_holds = isinstance(revs_baseline, list) and len(revs_baseline) == 0
d_pass = d_predicate_holds

# Sub-gate (e): ACR repository list does not contain "labacr".
# Single-path. Same cohort binding. Record-scoped: we parse the JSON
# array and check membership, not greppy substring matching.
e_predicate_holds = (
    isinstance(acr_repo_list_baseline, list)
    and TARGET_REPO_NAME not in acr_repo_list_baseline
)
e_pass = e_predicate_holds

# Extract observed smoking-gun message excerpt for the gate JSON record.
observed_first_smoking_gun_message = next(
    (msg for msg in ops_error_messages if SMOKING_GUN_TOKEN in msg),
    None,
)
observed_first_smoking_gun_excerpt = (
    observed_first_smoking_gun_message[:300]
    if isinstance(observed_first_smoking_gun_message, str)
    else None
)

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "acr_pull_failure_manifest_unknown",
    "hypothesis": "H1_failure_attribution",
    "claim": "failed_deployment_cohort_is_fully_attributable_to_manifest_resolution_failure",
    "claim_level": "Observed",
    "predicate_inputs": {
        "deployment_result_path": repo_rel(deployment_result_path),
        "deployment_ops_path": repo_rel(deployment_ops_path),
        "containerapp_baseline_path": repo_rel(containerapp_baseline_path),
        "revs_baseline_path": repo_rel(revs_baseline_path),
        "acr_repo_list_baseline_path": repo_rel(acr_repo_list_baseline_path),
    },
    "thresholds": {
        "smoking_gun_token": SMOKING_GUN_TOKEN,
        "target_repo_name": TARGET_REPO_NAME,
    },
    "cohort_binding_note": (
        "Sub-gates (b)-(e) are absence-style predicates that are interpretable as "
        "manifest-failure evidence ONLY in conjunction with sub-gate (a). A reader "
        "must not read 'revision list empty' or 'ACR repo absent' as evidence of "
        "this specific failure mode without also seeing the Failed deployment with "
        "MANIFEST_UNKNOWN. The predicate_inputs block records the deployment "
        "attribution and the absences in the same gate JSON so they cannot be "
        "interpreted separately."
    ),
    "sub_gate_a_predicate": (
        "Deployment failed (01-deployment-result.provisioningState == 'Failed') AND "
        "at least one per-operation record in 01-deployment-operations-failed.json "
        "contains 'MANIFEST_UNKNOWN' in statusMessage.error.message. "
        "Single-path per Oracle Q2 directive: 01-deployment-operations-failed.json "
        "is the MANIFEST_UNKNOWN canonical source; 01-deployment-result.json is "
        "optional corroboration only."
    ),
    "sub_gate_b_predicate": (
        "Container App resource provisioningState == 'Failed' "
        "(02-containerapp-show-baseline.provisioningState). Single-path."
    ),
    "sub_gate_c_predicate": (
        "Container App latestRevisionName is null "
        "(02-containerapp-show-baseline.latestRevisionName). Single-path."
    ),
    "sub_gate_d_predicate": (
        "Revision list is the empty array "
        "(03-revisions-list-baseline.json == []). Single-path."
    ),
    "sub_gate_e_predicate": (
        "ACR repository list does not contain 'labacr' "
        "(04-acr-repository-list-baseline.json membership check). "
        "Record-scoped per Lab 15 lesson 34: parsed JSON array membership, "
        "not greppy substring matching. Single-path."
    ),
    "sub_gate_a_deployment_failed_with_manifest_unknown": {
        "observed_deployment_provisioning_state": deployment_provisioning_state,
        "observed_ops_error_message_count": len(ops_error_messages),
        "observed_manifest_unknown_in_any_op": manifest_unknown_in_any_op,
        "observed_first_smoking_gun_excerpt": observed_first_smoking_gun_excerpt,
        "a_predicate_holds": a_predicate_holds,
        "a_pass": a_pass,
    },
    "sub_gate_b_containerapp_provisioning_state_failed": {
        "observed_containerapp_baseline_provisioning_state": containerapp_baseline_provisioning_state,
        "b_predicate_holds": b_predicate_holds,
        "b_pass": b_pass,
    },
    "sub_gate_c_latest_revision_name_null": {
        "observed_latest_revision_name": containerapp_baseline_latest_revision_name,
        "c_predicate_holds": c_predicate_holds,
        "c_pass": c_pass,
    },
    "sub_gate_d_revision_list_empty": {
        "observed_revision_list_length": len(revs_baseline) if isinstance(revs_baseline, list) else None,
        "observed_revision_list_is_list": isinstance(revs_baseline, list),
        "d_predicate_holds": d_predicate_holds,
        "d_pass": d_pass,
    },
    "sub_gate_e_acr_repo_absent": {
        "observed_acr_repo_list": acr_repo_list_baseline if isinstance(acr_repo_list_baseline, list) else None,
        "observed_acr_repo_list_length": len(acr_repo_list_baseline) if isinstance(acr_repo_list_baseline, list) else None,
        "observed_target_repo_present": (
            TARGET_REPO_NAME in acr_repo_list_baseline
            if isinstance(acr_repo_list_baseline, list) else None
        ),
        "e_predicate_holds": e_predicate_holds,
        "e_pass": e_pass,
    },
}
result["acr_pull_failure_h1_failure_attribution_sub_gates"] = {
    "a_deployment_failed_with_manifest_unknown": result["sub_gate_a_deployment_failed_with_manifest_unknown"]["a_pass"],
    "b_containerapp_provisioning_state_failed": result["sub_gate_b_containerapp_provisioning_state_failed"]["b_pass"],
    "c_latest_revision_name_null": result["sub_gate_c_latest_revision_name_null"]["c_pass"],
    "d_revision_list_empty": result["sub_gate_d_revision_list_empty"]["d_pass"],
    "e_acr_repo_absent": result["sub_gate_e_acr_repo_absent"]["e_pass"],
}
result["acr_pull_failure_h1_failure_attribution_all_subgates_pass"] = all(
    result["acr_pull_failure_h1_failure_attribution_sub_gates"].values()
)
result["gate_classification"] = "failed_deployment_cohort_is_fully_attributable_to_manifest_resolution_failure"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 32: recovery materialization gate ==="
UTC_NOW="$UTC_NOW" \
CONTAINERAPP_UPDATE_FILE="$CONTAINERAPP_UPDATE_FILE" \
REVS_AFTER_FIX_FILE="$REVS_AFTER_FIX_FILE" \
ACR_REPO_LIST_AFTER_FIX_FILE="$ACR_REPO_LIST_AFTER_FIX_FILE" \
ACR_REPO_TAGS_AFTER_FIX_FILE="$ACR_REPO_TAGS_AFTER_FIX_FILE" \
CURL_AFTER_FIX_FILE="$CURL_AFTER_FIX_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE32_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


def sample(items, n=5):
    return items[:n]


containerapp_update_path = pathlib.Path(os.environ["CONTAINERAPP_UPDATE_FILE"])
revs_after_fix_path = pathlib.Path(os.environ["REVS_AFTER_FIX_FILE"])
acr_repo_list_after_fix_path = pathlib.Path(os.environ["ACR_REPO_LIST_AFTER_FIX_FILE"])
acr_repo_tags_after_fix_path = pathlib.Path(os.environ["ACR_REPO_TAGS_AFTER_FIX_FILE"])
curl_after_fix_path = pathlib.Path(os.environ["CURL_AFTER_FIX_FILE"])

containerapp_update = json.loads(containerapp_update_path.read_text())
revs_after_fix = json.loads(revs_after_fix_path.read_text())
acr_repo_list_after_fix = json.loads(acr_repo_list_after_fix_path.read_text())
acr_repo_tags_after_fix = json.loads(acr_repo_tags_after_fix_path.read_text())
curl_after_fix = json.loads(curl_after_fix_path.read_text())

TARGET_REPO_NAME = "labacr"
TARGET_TAG = "v1"
STRONG_CURL_OK = 10
FALLBACK_CURL_OK_FLOOR = 8

# Sub-gate (a): containerapp update Succeeded AND latestRevisionName
# non-null. Single-path. BOTH-not-OR.
update_provisioning_state = containerapp_update.get("provisioningState")
update_latest_revision_name = containerapp_update.get("latestRevisionName")
a_predicate_holds = (
    update_provisioning_state == "Succeeded"
    and isinstance(update_latest_revision_name, str)
    and len(update_latest_revision_name) > 0
)
a_pass = a_predicate_holds

# Sub-gate (b): revision list has at least one Healthy + trafficWeight=100
# revision. Single-path. Record-scoped: iterate parsed records.
healthy_traffic100_revisions = [
    record
    for record in revs_after_fix
    if isinstance(record, dict)
    and record.get("healthState") == "Healthy"
    and record.get("trafficWeight") == 100
]
b_predicate_holds = len(healthy_traffic100_revisions) >= 1
b_pass = b_predicate_holds

# Sub-gate (c): curl_after_fix.requests_ok. Strong: == 10; Fallback: >= 8.
# This is the only dual-path sub-gate in Gate 32 per Oracle Q1 directive
# (dual-path only where equivalent manifestations exist; the curl floor
# tolerates transient platform startup variance without weakening the
# claim).
requests_ok = curl_after_fix.get("requests_ok")
requests_sent = curl_after_fix.get("requests_sent")
c_strong_path_requests_ok_eq_10 = requests_ok == STRONG_CURL_OK
c_fallback_path_requests_ok_ge_8 = (
    isinstance(requests_ok, int) and requests_ok >= FALLBACK_CURL_OK_FLOOR
)
c_pass = c_strong_path_requests_ok_eq_10 or c_fallback_path_requests_ok_ge_8

# Sub-gate (d): ACR repo list contains "labacr" AND tags contain "v1".
# Single-path. BOTH-not-OR. Record-scoped membership checks.
d_repo_present = (
    isinstance(acr_repo_list_after_fix, list)
    and TARGET_REPO_NAME in acr_repo_list_after_fix
)
d_tag_present = (
    isinstance(acr_repo_tags_after_fix, list)
    and TARGET_TAG in acr_repo_tags_after_fix
)
d_predicate_holds = d_repo_present and d_tag_present
d_pass = d_predicate_holds

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "acr_pull_failure_manifest_unknown",
    "hypothesis": "H2_recovery_materialization",
    "claim": "az_acr_build_plus_az_containerapp_update_materialized_a_healthy_serving_revision",
    "claim_level": "Observed",
    "predicate_inputs": {
        "containerapp_update_path": repo_rel(containerapp_update_path),
        "revs_after_fix_path": repo_rel(revs_after_fix_path),
        "acr_repo_list_after_fix_path": repo_rel(acr_repo_list_after_fix_path),
        "acr_repo_tags_after_fix_path": repo_rel(acr_repo_tags_after_fix_path),
        "curl_after_fix_path": repo_rel(curl_after_fix_path),
    },
    "thresholds": {
        "strong_curl_requests_ok": STRONG_CURL_OK,
        "fallback_curl_requests_ok_floor": FALLBACK_CURL_OK_FLOOR,
        "target_repo_name": TARGET_REPO_NAME,
        "target_tag": TARGET_TAG,
    },
    "sub_gate_a_predicate": (
        "08-containerapp-update-result.provisioningState == 'Succeeded' "
        "AND 08-containerapp-update-result.latestRevisionName is a non-empty "
        "string (BOTH-not-OR). Single-path."
    ),
    "sub_gate_b_predicate": (
        "10-revisions-list-after-fix.json contains at least one record with "
        "healthState == 'Healthy' AND trafficWeight == 100 (BOTH-not-OR). "
        "Record-scoped iteration. Single-path."
    ),
    "sub_gate_c_predicate": (
        "12-curl-after-fix.requests_ok == 10 (strong) or >= 8 (fallback). "
        "Dual-path: this is the only Gate 32 sub-gate with dual paths because "
        "the curl floor tolerates transient cold-start variance without "
        "weakening the recovery claim. Per Oracle Q1 directive — dual-path "
        "only where equivalent manifestations of the same claim exist."
    ),
    "sub_gate_d_predicate": (
        "11-acr-repository-list-after-fix.json contains 'labacr' AND "
        "11-acr-repository-show-tags-after-fix.json contains 'v1' (BOTH-not-OR). "
        "Record-scoped membership. Single-path."
    ),
    "sub_gate_a_update_succeeded_with_revision": {
        "observed_update_provisioning_state": update_provisioning_state,
        "observed_update_latest_revision_name": update_latest_revision_name,
        "a_predicate_holds": a_predicate_holds,
        "a_pass": a_pass,
    },
    "sub_gate_b_healthy_traffic_100_revision_exists": {
        "observed_total_revisions": len(revs_after_fix) if isinstance(revs_after_fix, list) else None,
        "observed_healthy_traffic_100_count": len(healthy_traffic100_revisions),
        "observed_first_5": sample(healthy_traffic100_revisions),
        "b_predicate_holds": b_predicate_holds,
        "b_pass": b_pass,
    },
    "sub_gate_c_curl_requests_ok": {
        "observed_requests_sent": requests_sent,
        "observed_requests_ok": requests_ok,
        "c_strong_path_requests_ok_eq_10": c_strong_path_requests_ok_eq_10,
        "c_fallback_path_requests_ok_ge_8": c_fallback_path_requests_ok_ge_8,
        "c_pass": c_pass,
    },
    "sub_gate_d_acr_repo_and_tag_present": {
        "observed_acr_repo_list": acr_repo_list_after_fix if isinstance(acr_repo_list_after_fix, list) else None,
        "observed_acr_repo_tags": acr_repo_tags_after_fix if isinstance(acr_repo_tags_after_fix, list) else None,
        "observed_repo_present": d_repo_present,
        "observed_tag_present": d_tag_present,
        "d_predicate_holds": d_predicate_holds,
        "d_pass": d_pass,
    },
}
result["acr_pull_failure_h2_recovery_materialization_sub_gates"] = {
    "a_update_succeeded_with_revision": result["sub_gate_a_update_succeeded_with_revision"]["a_pass"],
    "b_healthy_traffic_100_revision_exists": result["sub_gate_b_healthy_traffic_100_revision_exists"]["b_pass"],
    "c_curl_requests_ok": result["sub_gate_c_curl_requests_ok"]["c_pass"],
    "d_acr_repo_and_tag_present": result["sub_gate_d_acr_repo_and_tag_present"]["d_pass"],
}
result["acr_pull_failure_h2_recovery_materialization_all_subgates_pass"] = all(
    result["acr_pull_failure_h2_recovery_materialization_sub_gates"].values()
)
result["gate_classification"] = "az_acr_build_plus_az_containerapp_update_materialized_a_healthy_serving_revision"
print(json.dumps(result, indent=2))
PY

echo "=== Phase 33: in-place recovery continuity gate ==="
UTC_NOW="$UTC_NOW" \
CONTAINERAPP_BASELINE_FILE="$CONTAINERAPP_BASELINE_FILE" \
CONTAINERAPP_AFTER_FIX_FILE="$CONTAINERAPP_AFTER_FIX_FILE" \
REVS_AFTER_FIX_FILE="$REVS_AFTER_FIX_FILE" \
REVS_BASELINE_FILE="$REVS_BASELINE_FILE" \
REPO_RELATIVE_EVIDENCE_DIR="$REPO_RELATIVE_EVIDENCE_DIR" \
python3 <<'PY' > "$GATE33_FILE"
import json
import os
import pathlib


def repo_rel(path: pathlib.Path) -> str:
    return f"{os.environ['REPO_RELATIVE_EVIDENCE_DIR']}/{path.name}"


containerapp_baseline_path = pathlib.Path(os.environ["CONTAINERAPP_BASELINE_FILE"])
containerapp_after_fix_path = pathlib.Path(os.environ["CONTAINERAPP_AFTER_FIX_FILE"])
revs_after_fix_path = pathlib.Path(os.environ["REVS_AFTER_FIX_FILE"])
revs_baseline_path = pathlib.Path(os.environ["REVS_BASELINE_FILE"])

containerapp_baseline = json.loads(containerapp_baseline_path.read_text())
containerapp_after_fix = json.loads(containerapp_after_fix_path.read_text())
revs_after_fix = json.loads(revs_after_fix_path.read_text())
revs_baseline = json.loads(revs_baseline_path.read_text())

BAD_TAG_SUFFIX = ":does-not-exist"
GOOD_TAG_SUFFIX = ":v1"

# Sub-gate (a): same app identity. Baseline app name == after-fix app
# name. Single-path. BOTH names must be non-empty AND equal.
baseline_name = containerapp_baseline.get("name")
after_fix_name = containerapp_after_fix.get("name")
a_predicate_holds = (
    isinstance(baseline_name, str)
    and isinstance(after_fix_name, str)
    and len(baseline_name) > 0
    and baseline_name == after_fix_name
)
a_pass = a_predicate_holds

# Sub-gate (b): state transition. Baseline cohort is
# (provisioningState=Failed, latestRevisionName=null, revisions=[]).
# After-fix cohort is (provisioningState=Succeeded,
# latestRevisionName=<non-empty>, exactly one Healthy revision).
# Single-path. BOTH-not-OR across the cohort fields.
baseline_provisioning_state = containerapp_baseline.get("provisioningState")
baseline_latest_revision_name = containerapp_baseline.get("latestRevisionName")
baseline_revs_count = len(revs_baseline) if isinstance(revs_baseline, list) else None
after_fix_provisioning_state = containerapp_after_fix.get("provisioningState")
after_fix_latest_revision_name = containerapp_after_fix.get("latestRevisionName")
healthy_count = sum(
    1
    for record in revs_after_fix
    if isinstance(record, dict) and record.get("healthState") == "Healthy"
)
b_baseline_cohort_matches = (
    baseline_provisioning_state == "Failed"
    and baseline_latest_revision_name is None
    and baseline_revs_count == 0
)
b_after_fix_cohort_matches = (
    after_fix_provisioning_state == "Succeeded"
    and isinstance(after_fix_latest_revision_name, str)
    and len(after_fix_latest_revision_name) > 0
    and healthy_count >= 1
)
b_predicate_holds = b_baseline_cohort_matches and b_after_fix_cohort_matches
b_pass = b_predicate_holds


def extract_registry_login_server(image_value):
    """Return the registry login server prefix (everything before the
    first '/') if the image value parses as a registry-qualified image
    reference; otherwise return None. Record-scoped: this is string
    parsing on a single parsed JSON field value, not whole-file grep."""
    if not isinstance(image_value, str):
        return None
    if "/" not in image_value:
        return None
    return image_value.split("/", 1)[0]


# Sub-gate (c): image-tag delta with same ACR login server.
# Baseline image ends with ":does-not-exist", after-fix image ends with
# ":v1", AND both images parse to the same registry login server prefix.
# Single-path. Record-scoped: parses the .image field of each JSON
# document and splits on '/' to extract the registry prefix. This is
# the only "same-ACR" check retained per Oracle Q1 (the registry
# identity IS explicit in the parsed .image field, so the proof is
# sound). Drops the timestamp / no-recreation claims that Oracle Q1
# flagged as unsound for this evidence set.
baseline_image = containerapp_baseline.get("image")
after_fix_image = containerapp_after_fix.get("image")
baseline_registry = extract_registry_login_server(baseline_image)
after_fix_registry = extract_registry_login_server(after_fix_image)
baseline_ends_bad_tag = (
    isinstance(baseline_image, str) and baseline_image.endswith(BAD_TAG_SUFFIX)
)
after_fix_ends_good_tag = (
    isinstance(after_fix_image, str) and after_fix_image.endswith(GOOD_TAG_SUFFIX)
)
same_registry = (
    isinstance(baseline_registry, str)
    and isinstance(after_fix_registry, str)
    and baseline_registry == after_fix_registry
)
c_predicate_holds = (
    baseline_ends_bad_tag
    and after_fix_ends_good_tag
    and same_registry
)
c_pass = c_predicate_holds

result = {
    "utc_captured": os.environ["UTC_NOW"],
    "scenario": "acr_pull_failure_manifest_unknown",
    "hypothesis": "H_in_place_recovery_continuity",
    "claim": "recovery_is_in_place_same_app_same_registry_image_tag_only_delta",
    "claim_level": "Observed",
    "predicate_inputs": {
        "containerapp_baseline_path": repo_rel(containerapp_baseline_path),
        "containerapp_after_fix_path": repo_rel(containerapp_after_fix_path),
        "revs_after_fix_path": repo_rel(revs_after_fix_path),
        "revs_baseline_path": repo_rel(revs_baseline_path),
    },
    "thresholds": {
        "bad_tag_suffix": BAD_TAG_SUFFIX,
        "good_tag_suffix": GOOD_TAG_SUFFIX,
    },
    "sub_gate_a_predicate": (
        "Baseline app name == after-fix app name (both non-empty, both string-typed). "
        "Single-path. Record-scoped: parses .name field of "
        "02-containerapp-show-baseline.json and 09-containerapp-show-after-fix.json."
    ),
    "sub_gate_b_predicate": (
        "Baseline cohort (provisioningState=Failed, latestRevisionName=null, "
        "revisions=[]) transitions to after-fix cohort (provisioningState=Succeeded, "
        "latestRevisionName non-empty, at least one Healthy revision). "
        "BOTH-not-OR across cohort fields. Single-path."
    ),
    "sub_gate_c_predicate": (
        "Baseline .image endswith ':does-not-exist', after-fix .image endswith ':v1', "
        "and both .image fields parse to the same ACR login server prefix (everything "
        "before the first '/'). Single-path. Record-scoped: parses .image field of "
        "each JSON document; splits on '/' to extract registry prefix. Per Oracle Q1 "
        "directive: the registry identity is explicit in the parsed .image field so "
        "the same-registry proof is sound. Timestamp / no-recreation claims dropped "
        "per Oracle Q1 (not soundly evidenced by this cohort)."
    ),
    "sub_gate_a_same_app_identity": {
        "observed_baseline_name": baseline_name,
        "observed_after_fix_name": after_fix_name,
        "a_predicate_holds": a_predicate_holds,
        "a_pass": a_pass,
    },
    "sub_gate_b_state_transition": {
        "observed_baseline_provisioning_state": baseline_provisioning_state,
        "observed_baseline_latest_revision_name": baseline_latest_revision_name,
        "observed_baseline_revs_count": baseline_revs_count,
        "observed_after_fix_provisioning_state": after_fix_provisioning_state,
        "observed_after_fix_latest_revision_name": after_fix_latest_revision_name,
        "observed_after_fix_healthy_revision_count": healthy_count,
        "observed_baseline_cohort_matches": b_baseline_cohort_matches,
        "observed_after_fix_cohort_matches": b_after_fix_cohort_matches,
        "b_predicate_holds": b_predicate_holds,
        "b_pass": b_pass,
    },
    "sub_gate_c_image_tag_delta_same_registry": {
        "observed_baseline_image": baseline_image,
        "observed_after_fix_image": after_fix_image,
        "observed_baseline_registry": baseline_registry,
        "observed_after_fix_registry": after_fix_registry,
        "observed_baseline_ends_bad_tag": baseline_ends_bad_tag,
        "observed_after_fix_ends_good_tag": after_fix_ends_good_tag,
        "observed_same_registry": same_registry,
        "c_predicate_holds": c_predicate_holds,
        "c_pass": c_pass,
    },
}
result["acr_pull_failure_h_in_place_recovery_continuity_sub_gates"] = {
    "a_same_app_identity": result["sub_gate_a_same_app_identity"]["a_pass"],
    "b_state_transition": result["sub_gate_b_state_transition"]["b_pass"],
    "c_image_tag_delta_same_registry": result["sub_gate_c_image_tag_delta_same_registry"]["c_pass"],
}
result["acr_pull_failure_h_in_place_recovery_continuity_all_subgates_pass"] = all(
    result["acr_pull_failure_h_in_place_recovery_continuity_sub_gates"].values()
)
result["gate_classification"] = "recovery_is_in_place_same_app_same_registry_image_tag_only_delta"
print(json.dumps(result, indent=2))
PY

echo "=== Phase summary ==="
GATE30_FILE="$GATE30_FILE" \
GATE31_FILE="$GATE31_FILE" \
GATE32_FILE="$GATE32_FILE" \
GATE33_FILE="$GATE33_FILE" \
python3 <<'PY'
import json
import os
import pathlib
import sys

gates = [
    (
        "30",
        "cohort_integrity",
        pathlib.Path(os.environ["GATE30_FILE"]),
        "acr_pull_failure_h_cohort_integrity_sub_gates",
        "acr_pull_failure_h_cohort_integrity_all_subgates_pass",
    ),
    (
        "31",
        "failure_attribution",
        pathlib.Path(os.environ["GATE31_FILE"]),
        "acr_pull_failure_h1_failure_attribution_sub_gates",
        "acr_pull_failure_h1_failure_attribution_all_subgates_pass",
    ),
    (
        "32",
        "recovery_materialization",
        pathlib.Path(os.environ["GATE32_FILE"]),
        "acr_pull_failure_h2_recovery_materialization_sub_gates",
        "acr_pull_failure_h2_recovery_materialization_all_subgates_pass",
    ),
    (
        "33",
        "in_place_recovery_continuity",
        pathlib.Path(os.environ["GATE33_FILE"]),
        "acr_pull_failure_h_in_place_recovery_continuity_sub_gates",
        "acr_pull_failure_h_in_place_recovery_continuity_all_subgates_pass",
    ),
]

overall = True
print("gate | name                           | sub-gates                                                                                  | overall")
print("-----|--------------------------------|--------------------------------------------------------------------------------------------|--------")
for gate_id, name, path, sub_key, overall_key in gates:
    data = json.loads(path.read_text())
    subs = data[sub_key]
    sub_summary = ", ".join(f"{k}={'PASS' if v else 'FAIL'}" for k, v in subs.items())
    gate_pass = bool(data[overall_key])
    overall = overall and gate_pass
    print(f"{gate_id:>4} | {name:<30} | {sub_summary:<90} | {'PASS' if gate_pass else 'FAIL'}")

print("")
print(f"overall_phase_b_verdict={'PASS' if overall else 'FAIL'}")
sys.exit(0 if overall else 1)
PY
